Vesper::OrthographicCamera Class Reference
#include <OrthographicCamera.h>
Public Member Functions
OrthographicCamera (float left, float right, float bottom, float top)
void SetProjection (float left, float right, float bottom, float top)
void SetPosition (const glm::vec3 &position)
const glm::vec3 & GetPosition () const
void SetRotation (float rotation)
const float GetRotation () const
const glm::mat4 & GetProjectionMatrix () const
const glm::mat4 & GetViewMatrix () const
const glm::mat4 & GetViewProjectionMatrix () const
Private Member Functions
void RecalculateViewMatrix ()
Private Attributes
glm::mat4 m_ProjectionMatrix
glm::mat4 m_ViewMatrix
glm::mat4 m_ViewProjectionMatrix
glm::vec3 m_Position = { 0.0f, 0.0f, 0.0f }
float m_Rotation = 0.0f
Constructor & Destructor Documentation
OrthographicCamera()
Vesper::OrthographicCamera::OrthographicCamera (float left, float right, float bottom, float top)
        : m_ProjectionMatrix(glm::ortho(left, right, bottom, top, -1.0f, 1.0f)), m_ViewMatrix(1.0f)
    {
        VZ_PROFILE_FUNCTION();
        m_ViewProjectionMatrix = m_ProjectionMatrix * m_ViewMatrix;
    }
References OrthographicCamera().
Referenced by OrthographicCamera().
Member Function Documentation
GetPosition()
const glm::vec3 & Vesper::OrthographicCamera::GetPosition () const [inline]
{ return m_Position; }
GetProjectionMatrix()
const glm::mat4 & Vesper::OrthographicCamera::GetProjectionMatrix () const [inline]
{ return m_ProjectionMatrix; }
GetRotation()
const float Vesper::OrthographicCamera::GetRotation () const [inline]
{ return m_Rotation; }
References m_Rotation.
GetViewMatrix()
const glm::mat4 & Vesper::OrthographicCamera::GetViewMatrix () const [inline]
{ return m_ViewMatrix; }
GetViewProjectionMatrix()
const glm::mat4 & Vesper::OrthographicCamera::GetViewProjectionMatrix () const [inline]
{ return m_ViewProjectionMatrix; }
RecalculateViewMatrix()
void Vesper::OrthographicCamera::RecalculateViewMatrix () [private]
    {
        VZ_PROFILE_FUNCTION();
        glm::mat4 transform = glm::translate(glm::mat4(1.0f), m_Position) *
            glm::rotate(glm::mat4(1.0f), glm::radians(m_Rotation), glm::vec3(0, 0, 1));
        m_ViewMatrix = glm::inverse(transform);
        m_ViewProjectionMatrix = m_ProjectionMatrix * m_ViewMatrix;
    }
Referenced by SetPosition(), and SetRotation().
SetPosition()
void Vesper::OrthographicCamera::SetPosition (const glm::vec3 & position) [inline]
{ m_Position = position; RecalculateViewMatrix(); }
References RecalculateViewMatrix().
SetProjection()
void Vesper::OrthographicCamera::SetProjection (float left, float right, float bottom, float top)
    {
        VZ_PROFILE_FUNCTION();
        m_ProjectionMatrix = glm::ortho(left, right, bottom, top, -1.0f, 1.0f);
        m_ViewProjectionMatrix = m_ProjectionMatrix * m_ViewMatrix;
    }
SetRotation()
void Vesper::OrthographicCamera::SetRotation (float rotation) [inline]
{ m_Rotation = rotation; RecalculateViewMatrix(); }
References m_Rotation, and RecalculateViewMatrix().
Member Data Documentation
m_Position
glm::vec3 Vesper::OrthographicCamera::m_Position = { 0.0f, 0.0f, 0.0f } [private]
{ 0.0f, 0.0f, 0.0f };
m_ProjectionMatrix
glm::mat4 Vesper::OrthographicCamera::m_ProjectionMatrix [private]
m_Rotation
float Vesper::OrthographicCamera::m_Rotation = 0.0f [private]
Referenced by GetRotation(), and SetRotation().
m_ViewMatrix
glm::mat4 Vesper::OrthographicCamera::m_ViewMatrix [private]
m_ViewProjectionMatrix
glm::mat4 Vesper::OrthographicCamera::m_ViewProjectionMatrix [private]
The documentation for this class was generated from the following files:
Vesper/src/Vesper/Renderer/OrthographicCamera.h
Vesper/src/Vesper/Renderer/OrthographicCamera.cpp