Vesper::Window Class Reference
#include <Window.h>
Public Types
using EventCallbackFn = std::function<void(Event&)>
Public Member Functions
virtual ~Window ()
virtual void OnUpdate ()=0
virtual uint32_t GetWidth () const =0
virtual uint32_t GetHeight () const =0
virtual void SetEventCallback (const EventCallbackFn &callback)=0
virtual void SetVSync (bool enabled)=0
virtual bool IsVSync () const =0
virtual void * GetNativeWindow () const =0
Static Public Member Functions
static Scope< Window > Create (const WindowProps &props=WindowProps())
Member Typedef Documentation
EventCallbackFn
using Vesper::Window::EventCallbackFn = std::function<void(Event&)>
Constructor & Destructor Documentation
~Window()
virtual Vesper::Window::~Window () [inline], [virtual]
{}
Member Function Documentation
Create()
Scope< Window > Vesper::Window::Create (const WindowProps & props = WindowProps()) [static]
    {
        return CreateScope<WindowsWindow>(props);
    }
GetHeight()
virtual uint32_t Vesper::Window::GetHeight () const [pure virtual]
Implemented in Vesper::WindowsWindow.
Referenced by Vesper::ImGuiLayer::End().
GetNativeWindow()
virtual void * Vesper::Window::GetNativeWindow () const [pure virtual]
Implemented in Vesper::WindowsWindow.
Referenced by Vesper::Input::GetMousePosition(), Vesper::Input::IsKeyPressed(), and Vesper::Input::IsMouseButtonPressed().
GetWidth()
virtual uint32_t Vesper::Window::GetWidth () const [pure virtual]
Implemented in Vesper::WindowsWindow.
Referenced by Vesper::ImGuiLayer::End().
IsVSync()
virtual bool Vesper::Window::IsVSync () const [pure virtual]
Implemented in Vesper::WindowsWindow.
OnUpdate()
virtual void Vesper::Window::OnUpdate () [pure virtual]
Implemented in Vesper::WindowsWindow.
SetEventCallback()
virtual void Vesper::Window::SetEventCallback (const EventCallbackFn & callback) [pure virtual]
Implemented in Vesper::WindowsWindow.
SetVSync()
virtual void Vesper::Window::SetVSync (bool enabled) [pure virtual]
Implemented in Vesper::WindowsWindow.
The documentation for this class was generated from the following files:
Vesper/src/Vesper/App/Window.h
Vesper/src/Platform/Windows/WindowsWindow.cpp