Vesper::Renderer Class Reference
The main renderer class responsible for managing rendering operations.
#include <Renderer.h>
Classes
struct SceneData
Scene data structure containing view-projection matrix. More...
Static Public Member Functions
static void Init ()
Initializes the renderer.
static void OnWindowResize (uint32_t width, uint32_t height)
Handles window resize events by resizing the viewport.
static void BeginScene (OrthographicCamera &camera)
Begins a new scene with the given orthographic camera.
static void EndScene ()
Ends the current scene.
static void Submit (const Ref< Shader > &shader, const Ref< VertexArray > &vertexArray, const glm::mat4 &transform=glm::mat4(1.0f))
Submits a draw call with the specified shader, vertex array, and transform.
static RendererAPI::API GetAPI ()
Retrieves the current rendering API.
Static Private Attributes
static SceneData * s_SceneData = new Renderer::SceneData
Pointer to the current scene data.
Detailed Description
The main renderer class responsible for managing rendering operations.
Class Documentation
struct Vesper::Renderer::SceneData
Scene data structure containing view-projection matrix.
Class Members
mat4
ViewProjectionMatrix
The combined view-projection matrix for the scene.
Member Function Documentation
BeginScene()
void Vesper::Renderer::BeginScene (OrthographicCamera & camera) [static]
Begins a new scene with the given orthographic camera.
Parameters
camera The orthographic camera defining the view and projection for the scene.
Todo
Todo Support for other camera types.
    {
        VZ_PROFILE_FUNCTION();
        s_SceneData->ViewProjectionMatrix = camera.GetViewProjectionMatrix();
    }
References s_SceneData.
EndScene()
void Vesper::Renderer::EndScene () [static]
Ends the current scene.
Note
Currently does nothing as scene closure is automatic, but could be useful for a render interface
    {
        VZ_PROFILE_FUNCTION();
    }
GetAPI()
RendererAPI::API Vesper::Renderer::GetAPI () [inline], [static]
Retrieves the current rendering API.
{ return RendererAPI::GetAPI(); }
References Vesper::RendererAPI::GetAPI().
Referenced by Vesper::Framebuffer::Create(), Vesper::IndexBuffer::Create(), Vesper::Shader::Create(), Vesper::Shader::Create(), Vesper::Texture2D::Create(), Vesper::Texture2D::Create(), Vesper::UniformBuffer::Create(), Vesper::VertexArray::Create(), Vesper::VertexBuffer::Create(), and Vesper::VertexBuffer::Create().
Init()
void Vesper::Renderer::Init () [static]
Initializes the renderer.
Note
This initializes both the RenderCommand and Renderer2D systems.
    {
        VZ_PROFILE_FUNCTION();
        RenderCommand::Init();
        Renderer2D::Init();
    }
References Vesper::RenderCommand::Init(), and Vesper::Renderer2D::Init().
Referenced by Vesper::Application::Application().
OnWindowResize()
void Vesper::Renderer::OnWindowResize (uint32_t width, uint32_t height) [static]
Handles window resize events by resizing the viewport.
    {
        VZ_PROFILE_FUNCTION();
        RenderCommand::SetViewport(0, 0, width, height);
    }
References Vesper::RenderCommand::SetViewport().
Referenced by Vesper::Application::OnWindowResize().
Submit()
void Vesper::Renderer::Submit (const Ref< Shader > & shader, const Ref< VertexArray > & vertexArray, const glm::mat4 & transform = glm::mat4(1.0f)) [static]
Submits a draw call with the specified shader, vertex array, and transform.
Parameters
shader The shader to use for rendering.
vertexArray The vertex array to draw.
transform The transformation matrix to apply.
Todo
Todo Set up a command list to encapsulate this for draw order control
    {
        VZ_PROFILE_FUNCTION();
        shader->Bind();
        std::dynamic_pointer_cast<OpenGLShader>(shader)->UploadUniformMat4("u_ViewProjection", s_SceneData->ViewProjectionMatrix);
        std::dynamic_pointer_cast<OpenGLShader>(shader)->UploadUniformMat4("u_Transform", transform);
        vertexArray->Bind();
        RenderCommand::DrawIndexed(vertexArray);
    }
References s_SceneData.
Member Data Documentation
s_SceneData
Renderer::SceneData * Vesper::Renderer::s_SceneData = new Renderer::SceneData [static], [private]
Pointer to the current scene data.
Referenced by BeginScene(), and Submit().
The documentation for this class was generated from the following files:
Vesper/src/Vesper/Renderer/Renderer.h
Vesper/src/Vesper/Renderer/Renderer.cpp