Vesper::SceneCamera Class Reference
#include <SceneCamera.h>
Public Types
enum class ProjectionType { Perspective = 0
, Orthographic = 1
 }
Public Member Functions
SceneCamera ()
virtual ~SceneCamera ()=default
void SetOrthographic (float size, float nearClip, float farClip)
void SetPerspective (float verticalFOV, float nearClip, float farClip)
void SetViewportSize (uint32_t width, uint32_t height)
float GetPerspectiveVerticalFOV () const
void SetPerspectiveVerticalFOV (float verticalFov)
float GetPerspectiveNearClip () const
void SetPerspectiveNearClip (float nearClip)
float GetPerspectiveFarClip () const
void SetPerspectiveFarClip (float farClip)
float GetOrthographicSize () const
void SetOrthographicSize (float size)
float GetOrthographicNearClip () const
void SetOrthographicNearClip (float nearClip)
float GetOrthographicFarClip () const
void SetOrthographicFarClip (float farClip)
ProjectionType GetProjectionType () const
void SetProjectionType (ProjectionType type)
Public Member Functions inherited from Vesper::Camera
Camera ()=default
Camera (const glm::mat4 &projection)
~Camera ()=default
const glm::mat4 & GetProjection () const
Private Member Functions
void RecalculateProjection ()
Private Attributes
ProjectionType m_ProjectionType = ProjectionType::Orthographic
float m_PerspectiveFOV = glm::radians(45.0f)
float m_PerspectiveNear = 0.01f
float m_PerspectiveFar = 1000.0f
float m_OrthographicSize = 10.0f
float m_OrthographicNear = -1.0f
float m_OrthographicFar = 1.0f
float m_AspectRatio = 0.0f
Additional Inherited Members
Protected Attributes inherited from Vesper::Camera
glm::mat4 m_Projection = glm::mat4(1.0f)
Member Enumeration Documentation
ProjectionType
enum class Vesper::SceneCamera::ProjectionType [strong]
Enumerator
Perspective
Orthographic
{ Perspective = 0, Orthographic = 1 };
Constructor & Destructor Documentation
SceneCamera()
Vesper::SceneCamera::SceneCamera ()
    {
        RecalculateProjection();
    }
References RecalculateProjection().
~SceneCamera()
virtual Vesper::SceneCamera::~SceneCamera () [virtual], [default]
Member Function Documentation
GetOrthographicFarClip()
float Vesper::SceneCamera::GetOrthographicFarClip () const [inline]
{ return m_OrthographicFar; }
References m_OrthographicFar.
GetOrthographicNearClip()
float Vesper::SceneCamera::GetOrthographicNearClip () const [inline]
{ return m_OrthographicNear; }
References m_OrthographicNear.
GetOrthographicSize()
float Vesper::SceneCamera::GetOrthographicSize () const [inline]
{ return m_OrthographicSize; }
References m_OrthographicSize.
GetPerspectiveFarClip()
float Vesper::SceneCamera::GetPerspectiveFarClip () const [inline]
{ return m_PerspectiveFar; }
References m_PerspectiveFar.
GetPerspectiveNearClip()
float Vesper::SceneCamera::GetPerspectiveNearClip () const [inline]
{ return m_PerspectiveNear; }
References m_PerspectiveNear.
GetPerspectiveVerticalFOV()
float Vesper::SceneCamera::GetPerspectiveVerticalFOV () const [inline]
{ return m_PerspectiveFOV; }
GetProjectionType()
ProjectionType Vesper::SceneCamera::GetProjectionType () const [inline]
{ return m_ProjectionType; }
References m_ProjectionType.
RecalculateProjection()
void Vesper::SceneCamera::RecalculateProjection () [private]
    {
        if (m_ProjectionType == ProjectionType::Perspective)
        {
            m_Projection = glm::perspective(m_PerspectiveFOV, m_AspectRatio, m_PerspectiveNear, m_PerspectiveFar);
        }
        else
        {
            float orthoLeft = -m_OrthographicSize * m_AspectRatio * 0.5f;
            float orthoRight = m_OrthographicSize * m_AspectRatio * 0.5f;
            float orthoBottom = -m_OrthographicSize * 0.5f;
            float orthoTop = m_OrthographicSize * 0.5f;
            m_Projection = glm::ortho(orthoLeft, orthoRight,
                orthoBottom, orthoTop, m_OrthographicNear, m_OrthographicFar);
        }
    }
References m_AspectRatio, m_OrthographicSize, m_ProjectionType, and Perspective.
Referenced by SceneCamera(), SetOrthographic(), SetOrthographicFarClip(), SetOrthographicNearClip(), SetOrthographicSize(), SetPerspective(), SetPerspectiveFarClip(), SetPerspectiveNearClip(), SetPerspectiveVerticalFOV(), SetProjectionType(), and SetViewportSize().
SetOrthographic()
void Vesper::SceneCamera::SetOrthographic (float size, float nearClip, float farClip)
    {
        m_OrthographicSize = size;
        m_OrthographicNear = nearClip;
        m_OrthographicFar = farClip;
        RecalculateProjection();
    }
References m_OrthographicFar, m_OrthographicNear, m_OrthographicSize, and RecalculateProjection().
SetOrthographicFarClip()
void Vesper::SceneCamera::SetOrthographicFarClip (float farClip) [inline]
{ m_OrthographicFar = farClip; RecalculateProjection(); }
References m_OrthographicFar, and RecalculateProjection().
SetOrthographicNearClip()
void Vesper::SceneCamera::SetOrthographicNearClip (float nearClip) [inline]
{ m_OrthographicNear = nearClip; RecalculateProjection(); }
References m_OrthographicNear, and RecalculateProjection().
SetOrthographicSize()
void Vesper::SceneCamera::SetOrthographicSize (float size) [inline]
{ m_OrthographicSize = size; RecalculateProjection(); }
References m_OrthographicSize, and RecalculateProjection().
SetPerspective()
void Vesper::SceneCamera::SetPerspective (float verticalFOV, float nearClip, float farClip)
    {
        m_ProjectionType = ProjectionType::Perspective;
        m_PerspectiveFOV = verticalFOV;
        m_PerspectiveNear = nearClip;
        m_PerspectiveFar = farClip;
        RecalculateProjection();
    }
References m_PerspectiveFar, m_PerspectiveNear, m_ProjectionType, Perspective, and RecalculateProjection().
SetPerspectiveFarClip()
void Vesper::SceneCamera::SetPerspectiveFarClip (float farClip) [inline]
{ m_PerspectiveFar = farClip; RecalculateProjection(); }
References m_PerspectiveFar, and RecalculateProjection().
SetPerspectiveNearClip()
void Vesper::SceneCamera::SetPerspectiveNearClip (float nearClip) [inline]
{ m_PerspectiveNear = nearClip; RecalculateProjection(); }
References m_PerspectiveNear, and RecalculateProjection().
SetPerspectiveVerticalFOV()
void Vesper::SceneCamera::SetPerspectiveVerticalFOV (float verticalFov) [inline]
{ m_PerspectiveFOV = verticalFov; RecalculateProjection(); }
References RecalculateProjection().
SetProjectionType()
void Vesper::SceneCamera::SetProjectionType (ProjectionType type) [inline]
{ m_ProjectionType = type; RecalculateProjection(); }
References m_ProjectionType, and RecalculateProjection().
SetViewportSize()
void Vesper::SceneCamera::SetViewportSize (uint32_t width, uint32_t height)
    {
        m_AspectRatio = (float)width / (float)height;
        RecalculateProjection();
    }
References m_AspectRatio, and RecalculateProjection().
Member Data Documentation
m_AspectRatio
float Vesper::SceneCamera::m_AspectRatio = 0.0f [private]
Referenced by RecalculateProjection(), and SetViewportSize().
m_OrthographicFar
float Vesper::SceneCamera::m_OrthographicFar = 1.0f [private]
Referenced by GetOrthographicFarClip(), SetOrthographic(), and SetOrthographicFarClip().
m_OrthographicNear
float Vesper::SceneCamera::m_OrthographicNear = -1.0f [private]
Referenced by GetOrthographicNearClip(), SetOrthographic(), and SetOrthographicNearClip().
m_OrthographicSize
float Vesper::SceneCamera::m_OrthographicSize = 10.0f [private]
Referenced by GetOrthographicSize(), RecalculateProjection(), SetOrthographic(), and SetOrthographicSize().
m_PerspectiveFar
float Vesper::SceneCamera::m_PerspectiveFar = 1000.0f [private]
Referenced by GetPerspectiveFarClip(), SetPerspective(), and SetPerspectiveFarClip().
m_PerspectiveFOV
float Vesper::SceneCamera::m_PerspectiveFOV = glm::radians(45.0f) [private]
m_PerspectiveNear
float Vesper::SceneCamera::m_PerspectiveNear = 0.01f [private]
Referenced by GetPerspectiveNearClip(), SetPerspective(), and SetPerspectiveNearClip().
m_ProjectionType
ProjectionType Vesper::SceneCamera::m_ProjectionType = ProjectionType::Orthographic [private]
Referenced by GetProjectionType(), RecalculateProjection(), SetPerspective(), and SetProjectionType().
The documentation for this class was generated from the following files:
Vesper/src/Vesper/Scene/SceneCamera.h
Vesper/src/Vesper/Scene/SceneCamera.cpp