Vesper::Event Class Reference
Abstract base class for all events.
#include <Event.h>
Public Member Functions
virtual ~Event ()=default
virtual EventType GetEventType () const =0
Get the type of the event.
virtual const char * GetName () const =0
Get the name of the event.
virtual int GetCategoryFlags () const =0
Get the category flags of the event.
virtual std::string ToString () const
Convert the event to a string representation.
bool IsInCategory (EventCategory category)
Check if the event is in a specific category.
Public Attributes
bool Handled = false
Indicates whether the event has been handled.
Friends
class EventDispatcher
Detailed Description
Abstract base class for all events.
Constructor & Destructor Documentation
~Event()
virtual Vesper::Event::~Event () [virtual], [default]
Member Function Documentation
GetCategoryFlags()
virtual int Vesper::Event::GetCategoryFlags () const [pure virtual]
Get the category flags of the event.
Referenced by IsInCategory().
GetEventType()
virtual EventType Vesper::Event::GetEventType () const [pure virtual]
Get the type of the event.
GetName()
virtual const char * Vesper::Event::GetName () const [pure virtual]
Get the name of the event.
Referenced by ToString().
IsInCategory()
bool Vesper::Event::IsInCategory (EventCategory category) [inline]
Check if the event is in a specific category.
        {
            return GetCategoryFlags() & category;
        }
References GetCategoryFlags().
Referenced by Vesper::ImGuiLayer::OnEvent().
ToString()
virtual std::string Vesper::Event::ToString () const [inline], [virtual]
Convert the event to a string representation.
Reimplemented in Vesper::KeyPressedEvent, Vesper::KeyReleasedEvent, Vesper::KeyTypedEvent, Vesper::MouseButtonPressedEvent, Vesper::MouseButtonReleasedEvent, Vesper::MouseMovedEvent, Vesper::MouseScrolledEvent, and Vesper::WindowResizeEvent.
{ return GetName(); }
References GetName().
Friends And Related Symbol Documentation
EventDispatcher
friend class EventDispatcher [friend]
Member Data Documentation
Handled
bool Vesper::Event::Handled = false
Indicates whether the event has been handled.
Referenced by Vesper::ImGuiLayer::OnEvent().
The documentation for this class was generated from the following file:
Vesper/src/Vesper/Events/Event.h