Vesper::RenderCommand Class Reference
A static class that provides an interface for issuing rendering commands.
#include <RenderCommand.h>
Static Public Member Functions
static void Init ()
Initializes the rendering API.
static void SetViewport (uint32_t x, uint32_t y, uint32_t width, uint32_t height)
Sets the viewport dimensions for the renderer.
static void SetClearColor (const glm::vec4 &color)
Sets the clear color for the renderer.
static void Clear ()
Clears the rendering buffers.
static void DrawIndexed (const Ref< VertexArray > &vertexArray, uint32_t indexCount=0)
Draws indexed geometry using the specified vertex array and index count.
Static Private Attributes
static RendererAPI * s_RendererAPI = new OpenGLRendererAPI()
Detailed Description
A static class that provides an interface for issuing rendering commands.
Member Function Documentation
Clear()
void Vesper::RenderCommand::Clear () [inline], [static]
Clears the rendering buffers.
        {
            s_RendererAPI->Clear();
        }
References Vesper::RendererAPI::Clear(), and s_RendererAPI.
Referenced by Vesper::EditorLayer::OnUpdate().
DrawIndexed()
void Vesper::RenderCommand::DrawIndexed (const Ref< VertexArray > & vertexArray, uint32_t indexCount = 0) [inline], [static]
Draws indexed geometry using the specified vertex array and index count.
        {
            s_RendererAPI->DrawIndexed(vertexArray, indexCount);
        }
References s_RendererAPI.
Init()
void Vesper::RenderCommand::Init () [inline], [static]
Initializes the rendering API.
        {
            s_RendererAPI->Init();
        }
References Vesper::RendererAPI::Init(), and s_RendererAPI.
Referenced by Vesper::Renderer::Init().
SetClearColor()
void Vesper::RenderCommand::SetClearColor (const glm::vec4 & color) [inline], [static]
Sets the clear color for the renderer.
        {
            s_RendererAPI->SetClearColor(color);
        }
References s_RendererAPI.
SetViewport()
void Vesper::RenderCommand::SetViewport (uint32_t x, uint32_t y, uint32_t width, uint32_t height) [inline], [static]
Sets the viewport dimensions for the renderer.
        {
            s_RendererAPI->SetViewport(x, y, width, height);
        }
References s_RendererAPI, and Vesper::RendererAPI::SetViewport().
Referenced by Vesper::Renderer::OnWindowResize().
Member Data Documentation
s_RendererAPI
RendererAPI * Vesper::RenderCommand::s_RendererAPI = new OpenGLRendererAPI() [static], [private]
Referenced by Clear(), DrawIndexed(), Init(), SetClearColor(), and SetViewport().
The documentation for this class was generated from the following files:
Vesper/src/Vesper/Renderer/RenderCommand.h
Vesper/src/Vesper/Renderer/RenderCommand.cpp