Vesper::Layer Class Reference
Represents a reusable application layer that receives lifecycle callbacks (attach, detach, update, events, render, and ImGui render). Intended as a base class for concrete layers.
#include <Layer.h>
Public Member Functions
Layer (const std::string &name="Layer")
Constructs a Layer with an optional name for debugging purposes.
virtual ~Layer ()
virtual void OnAttach ()
Called when the layer is attached to the application.
virtual void OnDetach ()
Called when the layer is detached from the application.
virtual void OnUpdate (Timestep ts)
Called every frame to update the layer with the given timestep.
virtual void OnEvent (Event &event)
Called when an event is dispatched to the layer.
virtual void OnRender ()
Called when the layer should render its contents.
virtual void OnImGuiRender ()
Called when the layer should render its ImGui components.
const std::string & GetName () const
Retrieves the name of the layer for debugging purposes.
Protected Attributes
std::string m_DebugName
The name of the layer assigned at creation, used for debugging.
Detailed Description
Represents a reusable application layer that receives lifecycle callbacks (attach, detach, update, events, render, and ImGui render). Intended as a base class for concrete layers.
Constructor & Destructor Documentation
Layer()
Vesper::Layer::Layer (const std::string & name = "Layer")
Constructs a Layer with an optional name for debugging purposes.
Parameters
name The name of the layer, used for debugging.
        : m_DebugName(name)
    {
    }
References Layer().
Referenced by Layer().
~Layer()
Vesper::Layer::~Layer () [virtual]
    {
    }
Member Function Documentation
GetName()
const std::string & Vesper::Layer::GetName () const [inline]
Retrieves the name of the layer for debugging purposes.
{ return m_DebugName; }
OnAttach()
virtual void Vesper::Layer::OnAttach () [inline], [virtual]
Called when the layer is attached to the application.
Reimplemented in Sandbox2D, Vesper::EditorLayer, Vesper::ImGuiLayer, and Vesper::OpenGLImGuiLayer.
{};
Referenced by Vesper::Application::PushLayer(), and Vesper::Application::PushOverlay().
OnDetach()
virtual void Vesper::Layer::OnDetach () [inline], [virtual]
Called when the layer is detached from the application.
Reimplemented in Sandbox2D, Vesper::EditorLayer, Vesper::ImGuiLayer, and Vesper::OpenGLImGuiLayer.
{};
OnEvent()
virtual void Vesper::Layer::OnEvent (Event & event) [inline], [virtual]
Called when an event is dispatched to the layer.
Parameters
event The event being dispatched.
Reimplemented in ExampleLayer, ExampleLayer, Sandbox2D, Vesper::EditorLayer, Vesper::ImGuiLayer, and Vesper::OpenGLImGuiLayer.
{}
OnImGuiRender()
virtual void Vesper::Layer::OnImGuiRender () [inline], [virtual]
Called when the layer should render its ImGui components.
Reimplemented in ExampleLayer, ExampleLayer, Sandbox2D, Vesper::EditorLayer, Vesper::ImGuiLayer, and Vesper::OpenGLImGuiLayer.
{};
OnRender()
virtual void Vesper::Layer::OnRender () [inline], [virtual]
Called when the layer should render its contents.
{};
OnUpdate()
virtual void Vesper::Layer::OnUpdate (Timestep ts) [inline], [virtual]
Called every frame to update the layer with the given timestep.
Parameters
ts The timestep representing the time elapsed since the last update.
Reimplemented in ExampleLayer, ExampleLayer, Sandbox2D, and Vesper::EditorLayer.
{};
Member Data Documentation
m_DebugName
std::string Vesper::Layer::m_DebugName [protected]
The name of the layer assigned at creation, used for debugging.
The documentation for this class was generated from the following files:
Vesper/src/Vesper/App/Layer.h
Vesper/src/Vesper/App/Layer.cpp