Vesper::OrthographicCameraController Class Reference
#include <OrthographicCameraController.h>
Public Member Functions
OrthographicCameraController (float aspectRatio, bool rotation=false)
void OnUpdate (Timestep ts)
void OnEvent (Event &e)
void OnResize (float width, float height)
OrthographicCamera & GetCamera ()
const OrthographicCamera & GetCamera () const
OrthographicCameraBounds GetBounds () const
glm::vec3 GetPosition () const
void SetPosition (float x, float y)
void SetMoveSpeed (float speed)
float GetMoveSpeed () const
void SetRotation (float rotation)
float GetRotation () const
void SetRotationSpeed (float speed)
float GetRotationSpeed () const
float GetAspectRatio () const
void SetAspectRatio (float aspectRatio)
bool CanRotate () const
void SetCanRotate (bool canRotate)
void SetZoomLevel (float level)
float GetZoomLevel () const
void OnImGuiRender ()
TODO: move to an editor component that can be attached to any system (EditorAbstractionComp).
Private Member Functions
bool OnMouseScrolled (MouseScrolledEvent &e)
bool OnWindowResized (WindowResizeEvent &e)
void UpdateCameraBounds ()
void OnUpdateBounds ()
void CalculateView ()
Private Attributes
float m_AspectRatio
float m_ZoomLevel = 1.0f
OrthographicCamera camera
OrthographicCameraBounds m_Bounds
bool m_Rotation = true
glm::vec3 m_CameraPosition = { 0.0f, 0.0f, 0.0f }
float m_CameraRotation = 0.0f
float m_CameraMoveSpeed = 5.0f
float m_CameraRotationSpeed = 180.0f
Constructor & Destructor Documentation
OrthographicCameraController()
Vesper::OrthographicCameraController::OrthographicCameraController (float aspectRatio, bool rotation = false)
        : m_AspectRatio(aspectRatio), m_Rotation(rotation),
        camera(-m_AspectRatio * m_ZoomLevel, m_AspectRatio* m_ZoomLevel, -m_ZoomLevel, m_ZoomLevel),
        m_Bounds{ -m_AspectRatio * m_ZoomLevel, m_AspectRatio * m_ZoomLevel, -m_ZoomLevel, m_ZoomLevel }
    {
    }
References m_AspectRatio, m_Bounds, m_Rotation, m_ZoomLevel, and OrthographicCameraController().
Referenced by OrthographicCameraController().
Member Function Documentation
CalculateView()
void Vesper::OrthographicCameraController::CalculateView () [private]
    {
        UpdateCameraBounds();
        camera.SetProjection(m_Bounds.Left, m_Bounds.Right, m_Bounds.Bottom, m_Bounds.Top);
    }
References UpdateCameraBounds().
Referenced by OnMouseScrolled(), OnResize(), SetAspectRatio(), and SetZoomLevel().
CanRotate()
bool Vesper::OrthographicCameraController::CanRotate () const [inline]
{ return m_Rotation; }
References m_Rotation.
Referenced by OnImGuiRender().
GetAspectRatio()
float Vesper::OrthographicCameraController::GetAspectRatio () const
    {
        return m_AspectRatio;
    }
References m_AspectRatio.
GetBounds()
OrthographicCameraBounds Vesper::OrthographicCameraController::GetBounds () const [inline]
{ return m_Bounds; }
References m_Bounds.
GetCamera() [1/2]
OrthographicCamera & Vesper::OrthographicCameraController::GetCamera () [inline]
{ return camera; }
GetCamera() [2/2]
const OrthographicCamera & Vesper::OrthographicCameraController::GetCamera () const [inline]
{ return camera; }
GetMoveSpeed()
float Vesper::OrthographicCameraController::GetMoveSpeed () const [inline]
{ return m_CameraMoveSpeed; }
References m_CameraMoveSpeed.
Referenced by OnImGuiRender().
GetPosition()
glm::vec3 Vesper::OrthographicCameraController::GetPosition () const [inline]
{ return m_CameraPosition; }
GetRotation()
float Vesper::OrthographicCameraController::GetRotation () const [inline]
{ return m_CameraRotation; }
References m_CameraRotation.
Referenced by OnImGuiRender().
GetRotationSpeed()
float Vesper::OrthographicCameraController::GetRotationSpeed () const [inline]
{ return m_CameraRotationSpeed; }
References m_CameraRotationSpeed.
Referenced by OnImGuiRender().
GetZoomLevel()
float Vesper::OrthographicCameraController::GetZoomLevel () const [inline]
{ return m_ZoomLevel; }
References m_ZoomLevel.
OnEvent()
void Vesper::OrthographicCameraController::OnEvent (Event & e)
    {
        VZ_PROFILE_FUNCTION();
        EventDispatcher dispatcher(e);
        dispatcher.Dispatch<MouseScrolledEvent>(VZ_BIND_EVENT_FN(OrthographicCameraController::OnMouseScrolled));
        dispatcher.Dispatch<WindowResizeEvent>(VZ_BIND_EVENT_FN(OrthographicCameraController::OnWindowResized));
    }
References Vesper::EventDispatcher::EventDispatcher(), OnMouseScrolled(), and OnWindowResized().
OnImGuiRender()
void Vesper::OrthographicCameraController::OnImGuiRender ()
TODO: move to an editor component that can be attached to any system (EditorAbstractionComp).
    {
        //ImGui::Begin("Settings");
        static float camPos[3] = { GetPosition().x, GetPosition().y, GetPosition().z };
        if (ImGui::DragFloat3("Cam Pos", camPos, 0.1f)) {
            SetPosition(camPos[0], camPos[1]);
        }
        static float camMoveSpeed = GetMoveSpeed();
        if (ImGui::DragFloat("Cam Speed", &camMoveSpeed, 0.1f)) {
            SetMoveSpeed(camMoveSpeed);
        }
        ImGui::Separator();
        static bool rotate = CanRotate();
        if (ImGui::Checkbox("Rotate?", &rotate)) {
            SetCanRotate(rotate);
        }
        ImGui::Separator();
        static float camRot = GetRotation();
        if (ImGui::DragFloat("Cam Rotation", &camRot, 0.1f)) {
            SetRotation(camRot);
        }
        static float camRotSpeed = GetRotationSpeed();
        if (ImGui::DragFloat("Cam Rot Speed", &camRotSpeed, 1.0f)) {
            SetRotationSpeed(camRotSpeed);
        }
        //ImGui::End();
    }
References CanRotate(), GetMoveSpeed(), GetRotation(), GetRotationSpeed(), SetCanRotate(), SetMoveSpeed(), SetPosition(), SetRotation(), and SetRotationSpeed().
OnMouseScrolled()
bool Vesper::OrthographicCameraController::OnMouseScrolled (MouseScrolledEvent & e) [private]
    {
        VZ_PROFILE_FUNCTION();
        m_ZoomLevel -= e.GetYOffset() * 0.25f;
        m_ZoomLevel = std::max(m_ZoomLevel, 0.25f);
        CalculateView();
        return false;
    }
References CalculateView(), Vesper::MouseScrolledEvent::GetYOffset(), and m_ZoomLevel.
Referenced by OnEvent().
OnResize()
void Vesper::OrthographicCameraController::OnResize (float width, float height)
    {
        VZ_PROFILE_FUNCTION();
        m_AspectRatio = width / height;
        CalculateView();
    }
References CalculateView(), and m_AspectRatio.
Referenced by OnWindowResized().
OnUpdate()
void Vesper::OrthographicCameraController::OnUpdate (Timestep ts)
    {
        VZ_PROFILE_FUNCTION();
        if (Input::IsKeyPressed(VZ_KEY_A))
            m_CameraPosition.x -= m_CameraMoveSpeed * ts;
        else if (Input::IsKeyPressed(VZ_KEY_D))
            m_CameraPosition.x += m_CameraMoveSpeed * ts;
        if (Input::IsKeyPressed(VZ_KEY_W))
            m_CameraPosition.y += m_CameraMoveSpeed * ts;
        else if (Input::IsKeyPressed(VZ_KEY_S))
            m_CameraPosition.y -= m_CameraMoveSpeed * ts;
        if (m_Rotation)
        {
            if (Input::IsKeyPressed(VZ_KEY_Q))
                m_CameraRotation -= m_CameraRotationSpeed * ts;
            else if (Input::IsKeyPressed(VZ_KEY_E))
                m_CameraRotation += m_CameraRotationSpeed * ts;
            camera.SetRotation(m_CameraRotation);
        }
        camera.SetPosition(m_CameraPosition);
    }
References Vesper::Input::IsKeyPressed(), m_CameraRotation, m_CameraRotationSpeed, and m_Rotation.
OnUpdateBounds()
void Vesper::OrthographicCameraController::OnUpdateBounds () [private]
    {
        // Nothing for now
    }
Referenced by UpdateCameraBounds().
OnWindowResized()
bool Vesper::OrthographicCameraController::OnWindowResized (WindowResizeEvent & e) [private]
    {
        VZ_PROFILE_FUNCTION();
        OnResize((float)e.GetWidth(), (float)e.GetHeight());
        return false;
    }
References Vesper::WindowResizeEvent::GetHeight(), Vesper::WindowResizeEvent::GetWidth(), and OnResize().
Referenced by OnEvent().
SetAspectRatio()
void Vesper::OrthographicCameraController::SetAspectRatio (float aspectRatio)
    {
        m_AspectRatio = aspectRatio;
        CalculateView();
    }
References CalculateView(), and m_AspectRatio.
SetCanRotate()
void Vesper::OrthographicCameraController::SetCanRotate (bool canRotate) [inline]
{ m_Rotation = canRotate; }
References m_Rotation.
Referenced by OnImGuiRender().
SetMoveSpeed()
void Vesper::OrthographicCameraController::SetMoveSpeed (float speed)
    {
        m_CameraMoveSpeed = speed;
    }
References m_CameraMoveSpeed.
Referenced by OnImGuiRender().
SetPosition()
void Vesper::OrthographicCameraController::SetPosition (float x, float y)
    {
        m_CameraPosition = { x, y, 0.0f };
        camera.SetPosition(m_CameraPosition);
    }
Referenced by OnImGuiRender().
SetRotation()
void Vesper::OrthographicCameraController::SetRotation (float rotation)
    {
        m_CameraRotation = rotation;
        camera.SetRotation(m_CameraRotation);
    }
References m_CameraRotation.
Referenced by OnImGuiRender().
SetRotationSpeed()
void Vesper::OrthographicCameraController::SetRotationSpeed (float speed)
    {
        m_CameraRotationSpeed = speed;
    }
References m_CameraRotationSpeed.
Referenced by OnImGuiRender().
SetZoomLevel()
void Vesper::OrthographicCameraController::SetZoomLevel (float level) [inline]
{ m_ZoomLevel = level; CalculateView(); }
References CalculateView(), and m_ZoomLevel.
UpdateCameraBounds()
void Vesper::OrthographicCameraController::UpdateCameraBounds () [private]
    {
        m_Bounds.Left = -m_AspectRatio * m_ZoomLevel;
        m_Bounds.Right = m_AspectRatio * m_ZoomLevel;
        m_Bounds.Bottom = -m_ZoomLevel;
        m_Bounds.Top = m_ZoomLevel;
        OnUpdateBounds();
    }
References Vesper::OrthographicCameraBounds::Bottom, Vesper::OrthographicCameraBounds::Left, m_AspectRatio, m_Bounds, m_ZoomLevel, OnUpdateBounds(), Vesper::OrthographicCameraBounds::Right, and Vesper::OrthographicCameraBounds::Top.
Referenced by CalculateView().
Member Data Documentation
camera
OrthographicCamera Vesper::OrthographicCameraController::camera [private]
m_AspectRatio
float Vesper::OrthographicCameraController::m_AspectRatio [private]
Referenced by GetAspectRatio(), OnResize(), OrthographicCameraController(), SetAspectRatio(), and UpdateCameraBounds().
m_Bounds
OrthographicCameraBounds Vesper::OrthographicCameraController::m_Bounds [private]
Referenced by GetBounds(), OrthographicCameraController(), and UpdateCameraBounds().
m_CameraMoveSpeed
float Vesper::OrthographicCameraController::m_CameraMoveSpeed = 5.0f [private]
Referenced by GetMoveSpeed(), and SetMoveSpeed().
m_CameraPosition
glm::vec3 Vesper::OrthographicCameraController::m_CameraPosition = { 0.0f, 0.0f, 0.0f } [private]
{ 0.0f, 0.0f, 0.0f };
m_CameraRotation
float Vesper::OrthographicCameraController::m_CameraRotation = 0.0f [private]
Referenced by GetRotation(), OnUpdate(), and SetRotation().
m_CameraRotationSpeed
float Vesper::OrthographicCameraController::m_CameraRotationSpeed = 180.0f [private]
Referenced by GetRotationSpeed(), OnUpdate(), and SetRotationSpeed().
m_Rotation
bool Vesper::OrthographicCameraController::m_Rotation = true [private]
Referenced by CanRotate(), OnUpdate(), OrthographicCameraController(), and SetCanRotate().
m_ZoomLevel
float Vesper::OrthographicCameraController::m_ZoomLevel = 1.0f [private]
Referenced by GetZoomLevel(), OnMouseScrolled(), OrthographicCameraController(), SetZoomLevel(), and UpdateCameraBounds().
The documentation for this class was generated from the following files:
Vesper/src/Vesper/Renderer/OrthographicCameraController.h
Vesper/src/Vesper/Renderer/OrthographicCameraController.cpp