Vesper::Scene Class Reference
#include <Scene.h>
Public Member Functions
Scene ()
Scene (const std::string &name)
~Scene ()
Entity CreateEntity (const std::string &name=std::string())
Entity CreateEntity (const std::string &name, const std::string &uuid)
void DestroyEntity (Entity entity)
void OnUpdateRuntime (Timestep ts)
void OnUpdateEditor (Timestep ts, EditorCamera &camera)
void OnViewportResize (uint32_t width, uint32_t height)
Entity GetPrimaryCameraEntity ()
Private Member Functions
template<typename T>
void OnComponentAdded (Entity entity, T &component)
void SetName (const std::string &name)
const std::string & GetName () const
template<> void OnComponentAdded (Entity entity, UUIDComponent &component)
template<> void OnComponentAdded (Entity entity, NameComponent &component)
template<> void OnComponentAdded (Entity entity, TransformComponent &component)
template<> void OnComponentAdded (Entity entity, CameraComponent &component)
template<> void OnComponentAdded (Entity entity, SpriteRendererComponent &component)
template<> void OnComponentAdded (Entity entity, SubTextureComponent &component)
template<> void OnComponentAdded (Entity entity, TextureAnimationComponent &component)
template<> void OnComponentAdded (Entity entity, NativeScriptComponent &component)
template<> void OnComponentAdded (Entity entity, UUIDComponent &component)
template<> void OnComponentAdded (Entity entity, NameComponent &component)
template<> void OnComponentAdded (Entity entity, TransformComponent &component)
template<> void OnComponentAdded (Entity entity, CameraComponent &component)
template<> void OnComponentAdded (Entity entity, SpriteRendererComponent &component)
template<> void OnComponentAdded (Entity entity, SubTextureComponent &component)
template<> void OnComponentAdded (Entity entity, TextureAnimationComponent &component)
template<> void OnComponentAdded (Entity entity, NativeScriptComponent &component)
Private Attributes
std::string m_Name
entt::registry m_Registry
uint32_t m_ViewportWidth = 160
uint32_t m_ViewportHeight = 90
Friends
class Entity
class SceneSerializer
class SceneHierarchyPanel
Constructor & Destructor Documentation
Scene() [1/2]
Vesper::Scene::Scene ()
        : m_Name("Untitled Scene")
    {
        VZ_PROFILE_FUNCTION();
    }
References Scene().
Referenced by Scene().
Scene() [2/2]
Vesper::Scene::Scene (const std::string & name)
        : m_Name(name)
    {
    }
References Scene().
Referenced by Scene().
~Scene()
Vesper::Scene::~Scene ()
    {
    }
Member Function Documentation
CreateEntity() [1/2]
Entity Vesper::Scene::CreateEntity (const std::string & name, const std::string & uuid)
    {
        Entity entity = { m_Registry.create(), this };
        entity.AddComponent<TransformComponent>();
        auto& nameTag = entity.AddComponent<NameComponent>();
        nameTag.Name = name.empty() ? "Entity" + std::to_string(static_cast<std::uint32_t>(entity)) : name;
        entity.AddComponent<UUIDComponent>(uuid);
        return entity;
    }
CreateEntity() [2/2]
Entity Vesper::Scene::CreateEntity (const std::string & name = std::string())
    {
        Entity entity = { m_Registry.create(), this };
        entity.AddComponent<TransformComponent>();
        auto& nameTag = entity.AddComponent<NameComponent>();
        nameTag.Name = name.empty() ? "Entity" + std::to_string(static_cast<std::uint32_t>(entity)) : name;
        entity.AddComponent<UUIDComponent>();
        return entity;
    }
DestroyEntity()
void Vesper::Scene::DestroyEntity (Entity entity)
    {
        m_Registry.destroy(entity);
    }
GetName()
const std::string & Vesper::Scene::GetName () const [inline], [private]
{ return m_Name; }
GetPrimaryCameraEntity()
Entity Vesper::Scene::GetPrimaryCameraEntity ()
    {
        auto view = m_Registry.view<CameraComponent>();
        for (auto entity : view) {
            const auto& camera = view.get<CameraComponent>(entity);
            if (camera.Primary)
                return Entity{ entity, this };
        }
        return {};
    }
OnComponentAdded() [1/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, CameraComponent & component) [private]
                                                                                           {
        component.Camera.SetViewportSize(m_ViewportWidth, m_ViewportHeight);
    }
References m_ViewportHeight, and m_ViewportWidth.
OnComponentAdded() [2/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, CameraComponent & component) [private]
                                                                                           {
        component.Camera.SetViewportSize(m_ViewportWidth, m_ViewportHeight);
    }
OnComponentAdded() [3/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, NameComponent & component) [private]
                                                                                       {
    }
OnComponentAdded() [4/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, NameComponent & component) [private]
                                                                                       {
    }
OnComponentAdded() [5/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, NativeScriptComponent & component) [private]
                                                                                                       {
    }
OnComponentAdded() [6/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, NativeScriptComponent & component) [private]
                                                                                                       {
    }
OnComponentAdded() [7/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, SpriteRendererComponent & component) [private]
                                                                                                           {
    }
OnComponentAdded() [8/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, SpriteRendererComponent & component) [private]
                                                                                                           {
    }
OnComponentAdded() [9/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, SubTextureComponent & component) [private]
                                                                                                   {
        auto& src = entity.GetOrAddComponent<SpriteRendererComponent>();
        if (!src.TextureEnabled) src.TextureEnabled = true;
        component.SetTexture(src.Texture ? src.Texture : VZ_DEFAULT_TEXTURE);
    }
OnComponentAdded() [10/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, SubTextureComponent & component) [private]
                                                                                                   {
        auto& src = entity.GetOrAddComponent<SpriteRendererComponent>();
        if (!src.TextureEnabled) src.TextureEnabled = true;
        component.SetTexture(src.Texture ? src.Texture : VZ_DEFAULT_TEXTURE);
    }
OnComponentAdded() [11/17]
template<typename T>
void Vesper::Scene::OnComponentAdded (Entity entity, T & component) [private]
                                                            {
        static_assert(false);
    }
OnComponentAdded() [12/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, TextureAnimationComponent & component) [private]
                                                                                                               {
    }
OnComponentAdded() [13/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, TextureAnimationComponent & component) [private]
                                                                                                               {
    }
OnComponentAdded() [14/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, TransformComponent & component) [private]
                                                                                                 {
    }
OnComponentAdded() [15/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, TransformComponent & component) [private]
                                                                                                 {
    }
OnComponentAdded() [16/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, UUIDComponent & component) [private]
                                                                                       {
        // TODO: search registry to ensure unique UUID
    }
OnComponentAdded() [17/17]
template<>
void Vesper::Scene::OnComponentAdded (Entity entity, UUIDComponent & component) [private]
                                                                                       {
        // TODO: search registry to ensure unique UUID
    }
OnUpdateEditor()
void Vesper::Scene::OnUpdateEditor (Timestep ts, EditorCamera & camera)
    {
        VZ_PROFILE_FUNCTION();
        Renderer2D::BeginScene(camera);
        auto view = m_Registry.group<SpriteRendererComponent>();
        for (auto entity : view)
        {
            auto& transform = m_Registry.get<TransformComponent>(entity);
            auto& sprite = m_Registry.get<SpriteRendererComponent>(entity);
            // Do not render subtextures here
            auto stc = m_Registry.try_get<SubTextureComponent>(entity);
            if (stc) {
                continue;
            }
            if (sprite.TextureEnabled && !sprite.Texture)
                Renderer2D::DrawQuadWithTexture(transform.GetTransform(), VZ_DEFAULT_TEXTURE, sprite.TilingFactor, sprite.Color);
            else if (sprite.TextureEnabled && sprite.Texture)
                Renderer2D::DrawQuadWithTexture(transform.GetTransform(), sprite.Texture, sprite.TilingFactor, sprite.Color);
            else
                Renderer2D::DrawQuad(transform.GetTransform(), sprite.Color);
        }
        auto subTextureView = m_Registry.group<SubTextureComponent>();
        for (auto entity : subTextureView) {
            auto& transform = m_Registry.get<TransformComponent>(entity);
            auto& sprite = m_Registry.get<SpriteRendererComponent>(entity);
            auto& subTexture = m_Registry.get<SubTextureComponent>(entity);
            if (!sprite.TextureEnabled) sprite.TextureEnabled = true;
            if (subTexture.SubTexture == nullptr)
            {
                subTexture.SetTexture(VZ_DEFAULT_TEXTURE);
            }
            else {
                // TODO: find way to avoid this check every frame
                // Ensure the subtexture's texture matches the sprite's texture
                if (sprite.Texture && subTexture.SubTexture->GetTexture() != sprite.Texture) {
                    subTexture.SetTexture(sprite.Texture);
                }
            }
            Renderer2D::DrawQuadWithTexture(transform.GetTransform(), subTexture.GetSubTexture(), sprite.TilingFactor, sprite.Color);
        }
        Renderer2D::EndScene();
    }
References Vesper::Renderer2D::BeginScene(), and Vesper::Renderer2D::EndScene().
OnUpdateRuntime()
void Vesper::Scene::OnUpdateRuntime (Timestep ts)
TODO: Move to Scene::OnScenePlay()
    {
        VZ_PROFILE_FUNCTION();
        // Update scripts
        {
            m_Registry.view<NativeScriptComponent>().each([=](auto entity, NativeScriptComponent& nsc)
                {
                    if (!nsc.Instance)
                    {
                        nsc.Instance = nsc.InstantiateScript();
                        nsc.Instance->m_Entity = Entity{ entity, this };
                        nsc.Instance->OnCreate();
                    }
                    nsc.Instance->OnUpdate(ts);
                });
        }
        Camera* mainCamera = nullptr;
        glm::mat4* camTransform = nullptr;
        {
            auto view = m_Registry.view<TransformComponent, CameraComponent>();
            for (auto entity : view)
            {
                auto [transform, camera] = view.get<TransformComponent, CameraComponent>(entity);
                if (camera.Primary) {
                    mainCamera = &camera.Camera;
                    camTransform = &transform.GetTransform();
                    break;
                }
            }
        }
        if (!mainCamera)
            return;
        Renderer2D::BeginScene(mainCamera->GetProjection(), *camTransform);
        auto view = m_Registry.group<SpriteRendererComponent>();
        for (auto entity : view)
        {
            auto& transform = m_Registry.get<TransformComponent>(entity);
            auto& sprite = m_Registry.get<SpriteRendererComponent>(entity);
            // Do not render subtextures here
            auto stc = m_Registry.try_get<SubTextureComponent>(entity);
            if (stc) {
                continue;
            }
            if (sprite.TextureEnabled && !sprite.Texture)
                Renderer2D::DrawQuadWithTexture(transform.GetTransform(), VZ_DEFAULT_TEXTURE, sprite.TilingFactor, sprite.Color);
            else if (sprite.TextureEnabled && sprite.Texture)
                Renderer2D::DrawQuadWithTexture(transform.GetTransform(), sprite.Texture, sprite.TilingFactor, sprite.Color);
            else
                Renderer2D::DrawQuad(transform.GetTransform(), sprite.Color);
        }
        auto subTextureView = m_Registry.group<SubTextureComponent>();
        for (auto entity : subTextureView) {
            auto& transform = m_Registry.get<TransformComponent>(entity);
            auto& sprite = m_Registry.get<SpriteRendererComponent>(entity);
            auto& subTexture = m_Registry.get<SubTextureComponent>(entity);
            if (!sprite.TextureEnabled) sprite.TextureEnabled = true;
            if (subTexture.SubTexture == nullptr)
            {
                subTexture.SetTexture(VZ_DEFAULT_TEXTURE);
            }
            else {
                // Ensure the subtexture's texture matches the sprite's texture
                if (sprite.Texture && subTexture.SubTexture->GetTexture() != sprite.Texture) {
                    subTexture.SetTexture(sprite.Texture);
                }
            }
            Renderer2D::DrawQuadWithTexture(transform.GetTransform(), subTexture.GetSubTexture(), sprite.TilingFactor, sprite.Color);
        }
        //auto group1 = m_Registry.group<TextureAnimationComponent>();
        //for (auto entity : group1)
        //{
        // auto& transform = m_Registry.get<TransformComponent>(entity);
        // auto& texAnim = m_Registry.get<TextureAnimationComponent>(entity);
        // auto& sprite = m_Registry.get<SpriteRendererComponent>(entity);
        // texAnim.Update(ts.GetSeconds());
        // Renderer2D::DrawQuadWithTexture(transform.GetTransform(), texAnim.SubTextures[texAnim.CurrentFrame], 1.0f, sprite.Color);
        //}
        Renderer2D::EndScene();
    }
References Vesper::Renderer2D::EndScene().
OnViewportResize()
void Vesper::Scene::OnViewportResize (uint32_t width, uint32_t height)
    {
        m_ViewportWidth = width;
        m_ViewportHeight = height;
        // resize non fixed aspect ratio cameras
        auto view = m_Registry.view<CameraComponent>();
        for (auto entity : view)
        {
            auto& cameraComponent = view.get<CameraComponent>(entity);
            if (!cameraComponent.FixedAspectRatio)
                cameraComponent.Camera.SetViewportSize(width, height);
        }
    }
References m_ViewportHeight, and m_ViewportWidth.
SetName()
void Vesper::Scene::SetName (const std::string & name) [inline], [private]
TODO: friend class SceneCamera; TODO: friend class SceneRenderer;
{ m_Name = name; }
Friends And Related Symbol Documentation
Entity
friend class Entity [friend]
SceneHierarchyPanel
friend class SceneHierarchyPanel [friend]
SceneSerializer
friend class SceneSerializer [friend]
Member Data Documentation
m_Name
std::string Vesper::Scene::m_Name [private]
m_Registry
entt::registry Vesper::Scene::m_Registry [private]
m_ViewportHeight
uint32_t Vesper::Scene::m_ViewportHeight = 90 [private]
Referenced by OnComponentAdded(), and OnViewportResize().
m_ViewportWidth
uint32_t Vesper::Scene::m_ViewportWidth = 160 [private]
Referenced by OnComponentAdded(), and OnViewportResize().
The documentation for this class was generated from the following files:
Vesper/src/Vesper/Scene/Scene.h
Vesper/src/Vesper/Scene/Scene.cpp