Vesper::MouseScrolledEvent Class Reference
Event for registering mouse scroll wheel movement.
#include <MouseEvent.h>
Public Member Functions
MouseScrolledEvent (float xOffset, float yOffset)
Construct a MouseScrolledEvent with the specified x and y offsets.
float GetXOffset () const
Get the x offset of the mouse scroll.
float GetYOffset () const
Get the y offset of the mouse scroll.
std::string ToString () const override
Convert the event to a string representation.
Public Member Functions inherited from Vesper::Event
virtual ~Event ()=default
virtual EventType GetEventType () const =0
Get the type of the event.
virtual const char * GetName () const =0
Get the name of the event.
virtual int GetCategoryFlags () const =0
Get the category flags of the event.
bool IsInCategory (EventCategory category)
Check if the event is in a specific category.
Private Attributes
float m_XOffset
float m_YOffset
Additional Inherited Members
Public Attributes inherited from Vesper::Event
bool Handled = false
Indicates whether the event has been handled.
Detailed Description
Event for registering mouse scroll wheel movement.
Constructor & Destructor Documentation
MouseScrolledEvent()
Vesper::MouseScrolledEvent::MouseScrolledEvent (float xOffset, float yOffset) [inline]
Construct a MouseScrolledEvent with the specified x and y offsets.
Parameters
xOffset The offset of the mouse scroll in the x direction.
yOffset The offset of the mouse scroll in the y direction.
            : m_XOffset(xOffset), m_YOffset(yOffset) {
        }
References m_XOffset, and m_YOffset.
Member Function Documentation
GetXOffset()
float Vesper::MouseScrolledEvent::GetXOffset () const [inline]
Get the x offset of the mouse scroll.
{ return m_XOffset; }
References m_XOffset.
Referenced by ToString().
GetYOffset()
float Vesper::MouseScrolledEvent::GetYOffset () const [inline]
Get the y offset of the mouse scroll.
{ return m_YOffset; }
References m_YOffset.
Referenced by Vesper::EditorCamera::OnMouseScroll(), Vesper::OrthographicCameraController::OnMouseScrolled(), and ToString().
ToString()
std::string Vesper::MouseScrolledEvent::ToString () const [inline], [override], [virtual]
Convert the event to a string representation.
Reimplemented from Vesper::Event.
        {
            std::stringstream ss;
            ss << "MouseScrolledEvent: " << GetXOffset() << ", " << GetYOffset();
            return ss.str();
        }
References GetXOffset(), and GetYOffset().
Member Data Documentation
m_XOffset
float Vesper::MouseScrolledEvent::m_XOffset [private]
Referenced by GetXOffset(), and MouseScrolledEvent().
m_YOffset
float Vesper::MouseScrolledEvent::m_YOffset [private]
Referenced by GetYOffset(), and MouseScrolledEvent().
The documentation for this class was generated from the following file:
Vesper/src/Vesper/Events/MouseEvent.h