Sandbox2D Class Reference
#include <Sandbox2D.h>
Public Member Functions
Sandbox2D ()
virtual ~Sandbox2D ()
virtual void OnAttach () override
Called when the layer is attached to the application.
virtual void OnDetach () override
Called when the layer is detached from the application.
virtual void OnUpdate (Vesper::Timestep ts) override
Called every frame to update the layer with the given timestep.
virtual void OnImGuiRender () override
Called when the layer should render its ImGui components.
virtual void OnEvent (Vesper::Event &e) override
Called when an event is dispatched to the layer.
Public Member Functions inherited from Vesper::Layer
Layer (const std::string &name="Layer")
Constructs a Layer with an optional name for debugging purposes.
virtual ~Layer ()
virtual void OnRender ()
Called when the layer should render its contents.
const std::string & GetName () const
Retrieves the name of the layer for debugging purposes.
Private Attributes
Vesper::OrthographicCameraController m_CameraController
Vesper::Ref< Vesper::VertexArray > m_SquareVA
Vesper::Ref< Vesper::Shader > m_FlatColorShader
Vesper::Ref< Vesper::Texture2D > m_CheckerboardTexture
Vesper::Ref< Vesper::Texture2D > m_SpriteSheetFire
Vesper::Ref< Vesper::Texture2D > m_SpriteSheetTown
Vesper::Ref< Vesper::Texture2D > m_SpriteSheetCrystals
Vesper::Ref< Vesper::Texture2D > m_SpriteSheetRocks
Vesper::Ref< Vesper::Texture2D > m_SpriteSheetCursedLands
Vesper::Ref< Vesper::SubTexture2D > m_SubTextureFire
Vesper::Ref< Vesper::SubTexture2D > m_SubTextureTown
float m_textureScale = 1.0f
float m_squareRotation = 25.0f
float m_specialQuadRotation = 0.5f
int ParticleEmitCount = 100
bool scene1 = false
bool scene2 = false
bool scene3 = false
bool scene4 = true
glm::vec4 m_SquareColor = { 0.2f, 0.3f, 0.8f, 1.0f }
glm::vec4 m_TextureTintColor1 = { 1.0f, 1.0f, 1.0f, 1.0f }
glm::vec4 m_TextureTintColor2 = { 1.0f, 1.0f, 1.0f, 1.0f }
glm::vec4 m_BackgroundColor = { 0.1f, 0.1f, 0.1f, 1.0f }
glm::vec4 m_ClearColor = { 0.1f, 0.3f, 0.3f, 1.0f }
glm::vec4 m_SpecialQuadColor = { 0.9f, 0.2f, 0.8f, 1.0f }
bool m_UseSpecialQuadColor = false
Vesper::ParticleSystem m_ParticleSystem
Vesper::ParticleProps m_ParticleProps
std::unordered_map< char, Vesper::Ref< Vesper::SubTexture2D > > s_TextureMap
Additional Inherited Members
Protected Attributes inherited from Vesper::Layer
std::string m_DebugName
The name of the layer assigned at creation, used for debugging.
Constructor & Destructor Documentation
Sandbox2D()
Sandbox2D::Sandbox2D ()
    : Layer("Sandbox2D"), m_CameraController(1280.0f / 720.0f, true)
{
    VZ_PROFILE_FUNCTION();
}
References Sandbox2D().
Referenced by Sandbox2D(), and SandboxApp::SandboxApp().
~Sandbox2D()
Sandbox2D::~Sandbox2D () [virtual]
{
}
Member Function Documentation
OnAttach()
void Sandbox2D::OnAttach () [override], [virtual]
Called when the layer is attached to the application.
Reimplemented from Vesper::Layer.
{
    VZ_PROFILE_FUNCTION();
    //m_CheckerboardTexture = Vesper::Texture2D::Create("assets/textures/Checkerboard.png");
    //m_SpriteSheetFire = Vesper::Texture2D::Create("assets/textures/sheets/fire_01.png");
    //m_SpriteSheetTown = Vesper::Texture2D::Create("assets/textures/sheets/town_tilesheet.png");
    //m_SpriteSheetCrystals = Vesper::Texture2D::Create("assets/textures/sheets/craftpix/Crystals/Crystals.png");
    //m_SpriteSheetRocks = Vesper::Texture2D::Create("assets/textures/sheets/craftpix/Rocks/Rocks_source.png");
    //m_SpriteSheetCursedLands = Vesper::Texture2D::Create("assets/textures/sheets/craftpix/CursedLand/Tiled_files/Objects.png");
    //m_SubTextureFire = Vesper::SubTexture2D::CreateFromCoords(m_SpriteSheetFire, { 1, 0 }, { 128, 127 });
    //m_SubTextureTown = Vesper::SubTexture2D::CreateFromCoords(m_SpriteSheetTown, { 4.25, 0.75 }, { 64, 64 }, { 1, 1 });
    //s_TextureMap['F'] = Vesper::SubTexture2D::CreateFromCoords(m_SpriteSheetFire, { 1, 0 }, { 128, 127 });
    //s_TextureMap['G'] = Vesper::SubTexture2D::CreateFromCoords(m_SpriteSheetTown, { 4.25, 0.75 }, { 64, 64 }, { 1, 1 });
    //s_TextureMap['C'] = Vesper::SubTexture2D::CreateFromCoords(m_SpriteSheetCrystals, { 0, 1.25 }, { 64, 64 }, { 1, 1 });
    //s_TextureMap['R'] = Vesper::SubTexture2D::CreateFromCoords(m_SpriteSheetRocks, { 0, 3.75 }, { 64, 64 }, { 1, 1 });
    //s_TextureMap['P'] = Vesper::SubTexture2D::CreateFromCoords(m_SpriteSheetCursedLands, { 0, 1.875 }, { 128, 128 }, { 1, 1 });
    m_ParticleProps.Position = { 0.0f, 0.0f, 0.0f };
    m_ParticleProps.Velocity = { 0.0f, 0.0f, 0.0f };
    m_ParticleProps.VelocityVariation = { 1.0f, 1.0f, 0.0f };
    m_ParticleProps.ColorBegin = { 1.0f, 0.5f, 0.2f, 1.0f };
    m_ParticleProps.ColorEnd = { 0.2f, 0.3f, 0.8f, 1.0f };
    m_ParticleProps.SizeBegin = 0.5f;
    m_ParticleProps.SizeEnd = 0.0f;
    m_ParticleProps.LifeTime = 3.0f;
    m_ParticleProps.Rotation = 0.0f;
    m_ParticleProps.RotationVariation = 27.0f;
    m_ParticleSystem = Vesper::ParticleSystem(10000);
    m_ParticleSystem.SetParticleProps(m_ParticleProps);
    m_CameraController.SetZoomLevel(3.5f);
}
OnDetach()
void Sandbox2D::OnDetach () [override], [virtual]
Called when the layer is detached from the application.
Reimplemented from Vesper::Layer.
{
    VZ_PROFILE_FUNCTION();
}
OnEvent()
void Sandbox2D::OnEvent (Vesper::Event & event) [override], [virtual]
Called when an event is dispatched to the layer.
Parameters
event The event being dispatched.
Reimplemented from Vesper::Layer.
{
    m_CameraController.OnEvent(e);
}
OnImGuiRender()
void Sandbox2D::OnImGuiRender () [override], [virtual]
Called when the layer should render its ImGui components.
Reimplemented from Vesper::Layer.
{
    VZ_PROFILE_FUNCTION();
    {
        ImGui::Begin("Settings");
        ImGui::Text("Renderer2D Stats:");
        auto stats = Vesper::Renderer2D::GetStats();
        ImGui::Text("\tDraw Calls: %d", stats.DrawCalls);
        ImGui::Text("\tQuad Count: %d", stats.QuadCount);
        ImGui::Text("\tVertex Count: %d", stats.GetTotalVertexCount());
        ImGui::Text("\tIndex Count: %d", stats.GetTotalIndexCount());
        if (ImGui::ColorEdit4("Background Color", glm::value_ptr(m_ClearColor)))
        {
            Vesper::RenderCommand::SetClearColor(m_ClearColor);
        }
        ImGui::End();
    }
    Vesper::DisplayVesperInfo_ImGui();
}
References Vesper::DisplayVesperInfo_ImGui(), and Vesper::Renderer2D::GetStats().
OnUpdate()
void Sandbox2D::OnUpdate (Vesper::Timestep ts) [override], [virtual]
Called every frame to update the layer with the given timestep.
Parameters
ts The timestep representing the time elapsed since the last update.
Reimplemented from Vesper::Layer.
{
    VZ_PROFILE_FUNCTION();
    // Update
    m_CameraController.OnUpdate(ts);
    // Render
    Vesper::Renderer2D::ResetStats();
    {
        VZ_PROFILE_SCOPE("Renderer Prep");
        Vesper::RenderCommand::SetClearColor(m_ClearColor);
        Vesper::RenderCommand::Clear();
    }
    {
        static float rotation = 0.0f;
        rotation += ts * 50.0f;
        VZ_PROFILE_SCOPE("Renderer2D Draw");
        //if (scene1)
        //{
        // VZ_PROFILE_SCOPE("Scene 1");
        // Vesper::Renderer2D::BeginScene(m_CameraController.GetCamera());
        // // Checkerboard background
        // Vesper::Renderer2D::DrawQuadWithTexture({ 0.0f, 0.0f, -0.25f }, { 20.0f, 20.0f }, m_CheckerboardTexture, 10.0f, m_BackgroundColor);
        // // Squares
        // Vesper::Renderer2D::DrawQuadRotated({ 0.0f, 1.25f, -0.2f }, { 1.0f, 1.0f }, glm::radians(45.0f + m_squareRotation + rotation), m_SquareColor);
        // // Rotated Squares
        // if (m_UseSpecialQuadColor)
        // Vesper::Renderer2D::DrawQuadRotatedWithTexture({ 0.0f, 1.25f, -0.15f }, { 0.75f, 0.75f }, m_CheckerboardTexture, glm::radians(m_squareRotation * m_specialQuadRotation * rotation), m_textureScale, { 0.90f, 0.85f, 0.2f, 1.0f });
        // else
        // Vesper::Renderer2D::DrawQuadRotatedWithTexture({ 0.0f, 1.25f, -0.15f }, { 0.75f, 0.75f }, m_CheckerboardTexture, glm::radians(m_squareRotation * m_specialQuadRotation * rotation), m_textureScale, m_SpecialQuadColor);
        // Vesper::Renderer2D::DrawQuadRotatedWithTexture({ 2.0f, -0.25f, -0.15f }, { 1.0f, 1.0f }, m_CheckerboardTexture, glm::radians(m_squareRotation + rotation), m_textureScale, m_TextureTintColor1);
        // Vesper::Renderer2D::DrawQuadRotatedWithTexture({ -2.0f, -0.25f, -0.15f }, { 1.0f, 1.0f }, m_CheckerboardTexture, glm::radians(m_squareRotation + rotation), m_textureScale, m_TextureTintColor2);
        // for (int y = -5; y < 5; y++)
        // {
        // for (int x = -5; x < 5; x++)
        // {
        // glm::vec3 pos = glm::vec3(x * 0.15f, y * 0.15f, 0.0f);
        // Vesper::Renderer2D::DrawQuad(pos, { 2.5f, 2.5f }, { (x + 5) / 10.0f, 0.4f, (y + 5) / 10.0f, 0.55f });
        // }
        // }
        // Vesper::Renderer2D::EndScene();
        //}
        //if (scene2)
        //{
        // VZ_PROFILE_SCOPE("Scene 2");
        // Vesper::Renderer2D::BeginScene(m_CameraController.GetCamera());
        // // Sprite sheet drawn as full texture
        // Vesper::Renderer2D::DrawQuadWithTexture({ -1.0f, 1.5f, 0.5f }, { 1, 1 }, m_SpriteSheetFire, 1.0f, { 1.0f, 1.0f, 1.0f, 1.0f });
        // Vesper::Renderer2D::DrawQuadRotatedWithTexture({ 1.5f, 0.0f, 0.0f }, { 1.78f, 1.0f }, m_SpriteSheetTown, 0, 1.0f, { 1.0f, 1.0f, 1.0f, 1.0f });
        // // Sprite sheet drawn as full texture rotated
        // Vesper::Renderer2D::DrawQuadRotatedWithTexture({ -1.5f, 0.0f, 0.0f }, { 1.78f, 1.0f }, m_SpriteSheetTown, glm::radians(-rotation), 1.0f, { 1.0f, 1.0f, 1.0f, 1.0f });
        // // Sub texture from tilesheet
        // Vesper::Renderer2D::DrawQuadWithTexture({ 2.0f, -1.5f, 0.0f }, { 1.0f, 1.0f }, m_SubTextureTown, 1.0f, { 1.0f, 1.0f, 1.0f, 1.0f });
        // // Grid of sub textures from tilesheet
        // for (int y = -5; y < 5; y++)
        // {
        // for (int x = -5; x < 5; x++)
        // {
        // glm::vec3 pos = glm::vec3(x * 0.09f, y * 0.09f, -0.09f);
        // Vesper::Renderer2D::DrawQuadWithTexture(pos, { 0.1f, 0.1f }, m_SubTextureTown, 1.0f, glm::vec4(1.0f));
        // }
        // }
        // /// TODO: get it to animate through texture sheet sub texture indices
        // Vesper::Renderer2D::DrawQuadRotatedWithTexture({ 0.0f, -1.5f, 0.0f }, { 1.0f, 1.0f }, m_SubTextureFire, 0, 1.0f, { 1.0f, 1.0f, 1.0f, 1.0f });
        // Vesper::Renderer2D::EndScene();
        //}
        //if (scene3)
        //{
        // VZ_PROFILE_SCOPE("Scene 3");
        // Vesper::Renderer2D::BeginScene(m_CameraController.GetCamera());
        // for (uint32_t y = 0; y < s_MapHeight; y++)
        // {
        // for (uint32_t x = 0; x < s_MapWidth; x++)
        // {
        // char tileChar = s_MapTiles[x + y * s_MapWidth];
        // Vesper::Ref<Vesper::SubTexture2D> texture;
        // if (s_TextureMap.find(tileChar) != s_TextureMap.end())
        // texture = s_TextureMap[tileChar];
        // else
        // texture = s_TextureMap['G']; // Default to grass
        // Vesper::Renderer2D::DrawQuadWithTexture({ x - s_MapWidth / 2.0f, s_MapHeight - y - s_MapHeight / 2.0f, 0.1f }, { 1.0f, 1.0f }, texture, 1.0f, glm::vec4(1.0f));
        // }
        // }
        // Vesper::Renderer2D::EndScene();
        //}
        //if (scene4)
        //{
            VZ_PROFILE_SCOPE("Particle Scene");
            Vesper::Renderer2D::BeginScene(m_CameraController.GetCamera());
            for (float y = -5.0f; y < 5.0f; y += 0.5f)
            {
                for (float x = -5.0f; x < 5.0f; x += 0.5f)
                {
                    glm::vec4 color = { (x + 5.0f) / 10.0f, 0.4f,(y + 5.0f) / 10.0f, 0.35f };
                    Vesper::Renderer2D::DrawQuad({ x, y, -0.5 }, { 0.45f, 0.45f }, color);
                }
            }
            if (Vesper::Input::IsMouseButtonPressed(Vesper::Mouse::ButtonLeft))
            {
                glm::vec2 mousePos = Vesper::Input::GetMousePosition();
                auto width = Vesper::Application::Get().GetWindow().GetWidth();
                auto height = Vesper::Application::Get().GetWindow().GetHeight();
                auto bounds = m_CameraController.GetBounds();
                m_ParticleProps.Position.x = (mousePos.x / width) * bounds.GetWidth() - bounds.GetWidth() * 0.5f + m_CameraController.GetPosition().x;
                m_ParticleProps.Position.y = bounds.GetHeight() * 0.5f - (mousePos.y / height) * bounds.GetHeight() + m_CameraController.GetPosition().y;
                for (int i = 0; i < ParticleEmitCount; i++) {
                    m_ParticleSystem.Emit(m_ParticleProps);
                }
            }
            m_ParticleSystem.OnUpdate(ts);
            m_ParticleSystem.OnRender(m_CameraController.GetCamera());
            Vesper::Renderer2D::EndScene();
        //}
    }
}
References Vesper::Mouse::ButtonLeft, Vesper::RenderCommand::Clear(), Vesper::Renderer2D::EndScene(), Vesper::Application::Get(), Vesper::Window::GetHeight(), Vesper::Window::GetWidth(), Vesper::Application::GetWindow(), Vesper::Input::IsMouseButtonPressed(), ParticleEmitCount, and Vesper::Renderer2D::ResetStats().
Member Data Documentation
m_BackgroundColor
glm::vec4 Sandbox2D::m_BackgroundColor = { 0.1f, 0.1f, 0.1f, 1.0f } [private]
{ 0.1f, 0.1f, 0.1f, 1.0f };
m_CameraController
Vesper::OrthographicCameraController Sandbox2D::m_CameraController [private]
m_CheckerboardTexture
Vesper::Ref<Vesper::Texture2D> Sandbox2D::m_CheckerboardTexture [private]
m_ClearColor
glm::vec4 Sandbox2D::m_ClearColor = { 0.1f, 0.3f, 0.3f, 1.0f } [private]
{ 0.1f, 0.3f, 0.3f, 1.0f };
m_FlatColorShader
Vesper::Ref<Vesper::Shader> Sandbox2D::m_FlatColorShader [private]
m_ParticleProps
Vesper::ParticleProps Sandbox2D::m_ParticleProps [private]
m_ParticleSystem
Vesper::ParticleSystem Sandbox2D::m_ParticleSystem [private]
m_SpecialQuadColor
glm::vec4 Sandbox2D::m_SpecialQuadColor = { 0.9f, 0.2f, 0.8f, 1.0f } [private]
{ 0.9f, 0.2f, 0.8f, 1.0f };
m_specialQuadRotation
float Sandbox2D::m_specialQuadRotation = 0.5f [private]
m_SpriteSheetCrystals
Vesper::Ref<Vesper::Texture2D> Sandbox2D::m_SpriteSheetCrystals [private]
m_SpriteSheetCursedLands
Vesper::Ref<Vesper::Texture2D> Sandbox2D::m_SpriteSheetCursedLands [private]
m_SpriteSheetFire
Vesper::Ref<Vesper::Texture2D> Sandbox2D::m_SpriteSheetFire [private]
m_SpriteSheetRocks
Vesper::Ref<Vesper::Texture2D> Sandbox2D::m_SpriteSheetRocks [private]
m_SpriteSheetTown
Vesper::Ref<Vesper::Texture2D> Sandbox2D::m_SpriteSheetTown [private]
m_SquareColor
glm::vec4 Sandbox2D::m_SquareColor = { 0.2f, 0.3f, 0.8f, 1.0f } [private]
{ 0.2f, 0.3f, 0.8f, 1.0f };
m_squareRotation
float Sandbox2D::m_squareRotation = 25.0f [private]
m_SquareVA
Vesper::Ref<Vesper::VertexArray> Sandbox2D::m_SquareVA [private]
m_SubTextureFire
Vesper::Ref<Vesper::SubTexture2D> Sandbox2D::m_SubTextureFire [private]
m_SubTextureTown
Vesper::Ref<Vesper::SubTexture2D> Sandbox2D::m_SubTextureTown [private]
m_textureScale
float Sandbox2D::m_textureScale = 1.0f [private]
m_TextureTintColor1
glm::vec4 Sandbox2D::m_TextureTintColor1 = { 1.0f, 1.0f, 1.0f, 1.0f } [private]
{ 1.0f, 1.0f, 1.0f, 1.0f };
m_TextureTintColor2
glm::vec4 Sandbox2D::m_TextureTintColor2 = { 1.0f, 1.0f, 1.0f, 1.0f } [private]
{ 1.0f, 1.0f, 1.0f, 1.0f };
m_UseSpecialQuadColor
bool Sandbox2D::m_UseSpecialQuadColor = false [private]
ParticleEmitCount
int Sandbox2D::ParticleEmitCount = 100 [private]
Referenced by OnUpdate().
s_TextureMap
std::unordered_map<char, Vesper::Ref<Vesper::SubTexture2D> > Sandbox2D::s_TextureMap [private]
scene1
bool Sandbox2D::scene1 = false [private]
scene2
bool Sandbox2D::scene2 = false [private]
scene3
bool Sandbox2D::scene3 = false [private]
scene4
bool Sandbox2D::scene4 = true [private]
The documentation for this class was generated from the following files:
Sandbox/src/Sandbox2D.h
Sandbox/src/Sandbox2D.cpp