Vesper::KeyEvent Class Reference
Base class for keyboard events.
#include <KeyEvent.h>
Public Member Functions
int GetKeyCode () const
Get the key code associated with the event.
Public Member Functions inherited from Vesper::Event
virtual ~Event ()=default
virtual EventType GetEventType () const =0
Get the type of the event.
virtual const char * GetName () const =0
Get the name of the event.
virtual int GetCategoryFlags () const =0
Get the category flags of the event.
virtual std::string ToString () const
Convert the event to a string representation.
bool IsInCategory (EventCategory category)
Check if the event is in a specific category.
Protected Member Functions
KeyEvent (int keycode)
Construct a KeyEvent with the specified key code.
Protected Attributes
int m_KeyCode
Additional Inherited Members
Public Attributes inherited from Vesper::Event
bool Handled = false
Indicates whether the event has been handled.
Detailed Description
Base class for keyboard events.
Constructor & Destructor Documentation
KeyEvent()
Vesper::KeyEvent::KeyEvent (int keycode) [inline], [protected]
Construct a KeyEvent with the specified key code.
Parameters
keycode The key code associated with the event. Restricted specific construction to derived classes.
            : m_KeyCode(keycode) {}
References m_KeyCode.
Referenced by Vesper::KeyPressedEvent::KeyPressedEvent(), Vesper::KeyReleasedEvent::KeyReleasedEvent(), and Vesper::KeyTypedEvent::KeyTypedEvent().
Member Function Documentation
GetKeyCode()
int Vesper::KeyEvent::GetKeyCode () const [inline]
Get the key code associated with the event.
{ return m_KeyCode; }
References m_KeyCode.
Referenced by Vesper::EditorLayer::OnKeyPressed().
Member Data Documentation
m_KeyCode
int Vesper::KeyEvent::m_KeyCode [protected]
Referenced by GetKeyCode(), KeyEvent(), Vesper::KeyPressedEvent::ToString(), Vesper::KeyReleasedEvent::ToString(), and Vesper::KeyTypedEvent::ToString().
The documentation for this class was generated from the following file:
Vesper/src/Vesper/Events/KeyEvent.h