Vesper::EventDispatcher Class Reference
Stack-based templated event dispatcher.
#include <Event.h>
Public Member Functions
EventDispatcher (Event &event)
Construct an EventDispatcher for a specific event.
template<typename T>
bool Dispatch (EventFn< T > func)
Dispatch the event to the appropriate handler if the types match.
Private Types
template<typename T>
using EventFn = std::function<bool(T&)>
Type alias for event handling functions.
Private Attributes
Event & m_Event
The event to be dispatched.
Detailed Description
Stack-based templated event dispatcher.
Member Typedef Documentation
EventFn
template<typename T>
using Vesper::EventDispatcher::EventFn = std::function<bool(T&)> [private]
Type alias for event handling functions.
Constructor & Destructor Documentation
EventDispatcher()
Vesper::EventDispatcher::EventDispatcher (Event & event) [inline]
Construct an EventDispatcher for a specific event.
Parameters
event The event to dispatch.
            : m_Event(event)
        {
        }
References m_Event.
Referenced by Vesper::Application::OnEvent(), Vesper::EditorCamera::OnEvent(), Vesper::EditorLayer::OnEvent(), and Vesper::OrthographicCameraController::OnEvent().
Member Function Documentation
Dispatch()
template<typename T>
bool Vesper::EventDispatcher::Dispatch (EventFn< T > func) [inline]
Dispatch the event to the appropriate handler if the types match.
Template Parameters
T The type of the event to dispatch.
Parameters
func The function to handle the event.
Returns
True if the event was handled, false otherwise.
        {
            if (m_Event.GetEventType() == T::GetStaticType())
            {
                m_Event.Handled = func(*(T*)&m_Event);
                return true;
            }
            return false;
        }
Member Data Documentation
m_Event
Event& Vesper::EventDispatcher::m_Event [private]
The event to be dispatched.
Referenced by EventDispatcher().
The documentation for this class was generated from the following file:
Vesper/src/Vesper/Events/Event.h