Vesper::VesperEditor Class Reference
Public Member Functions
VesperEditor ()
~VesperEditor ()
VesperEditor ()
~VesperEditor ()
Public Member Functions inherited from Vesper::Application
Application (const std::string &name="")
Constructs the Application with the given name.
virtual ~Application ()
void Run ()
Starts the main application loop.
void OnEvent (Event &e)
Handles incoming events and dispatches them to the appropriate handlers.
void PushLayer (Layer *layer)
Adds a layer to the application layer stack.
void PushOverlay (Layer *overlay)
Adds an overlay layer to the application layer stack.
void Close ()
Closes the application.
ImGuiLayer * GetImGuiLayer ()
Retrieves the ImGui layer.
Window & GetWindow ()
Retrieves the application window.
Additional Inherited Members
Static Public Member Functions inherited from Vesper::Application
static Application & Get ()
Retrieves the singleton instance of the Application.
Constructor & Destructor Documentation
VesperEditor() [1/2]
Vesper::VesperEditor::VesperEditor () [inline]
            : Application("Vesper Editor")
        {
            PushLayer(new EditorLayer());
        }
References Vesper::EditorLayer::EditorLayer(), and Vesper::Application::PushLayer().
Referenced by Vesper::CreateApplication().
~VesperEditor() [1/2]
Vesper::VesperEditor::~VesperEditor () [inline]
                        {
        }
VesperEditor() [2/2]
Vesper::VesperEditor::VesperEditor () [inline]
            : Application("Vesper Editor")
        {
            PushLayer(new EditorLayer());
        }
~VesperEditor() [2/2]
Vesper::VesperEditor::~VesperEditor () [inline]
                        {
        }
The documentation for this class was generated from the following file:
Vesper-Editor/src/VesperEditorApp.cpp