Vesper::MouseButtonEvent Class Reference
Base class for mouse button events.
#include <MouseEvent.h>
Public Member Functions
int GetMouseButton () const
Get the mouse button associated with the event.
Public Member Functions inherited from Vesper::Event
virtual ~Event ()=default
virtual EventType GetEventType () const =0
Get the type of the event.
virtual const char * GetName () const =0
Get the name of the event.
virtual int GetCategoryFlags () const =0
Get the category flags of the event.
virtual std::string ToString () const
Convert the event to a string representation.
bool IsInCategory (EventCategory category)
Check if the event is in a specific category.
Protected Member Functions
MouseButtonEvent (int button)
Construct a MouseButtonEvent with the specified button.
Protected Attributes
int m_Button
Additional Inherited Members
Public Attributes inherited from Vesper::Event
bool Handled = false
Indicates whether the event has been handled.
Detailed Description
Base class for mouse button events.
Constructor & Destructor Documentation
MouseButtonEvent()
Vesper::MouseButtonEvent::MouseButtonEvent (int button) [inline], [protected]
Construct a MouseButtonEvent with the specified button.
Parameters
button The mouse button associated with the event. Restricted specific construction to derived classes.
            : m_Button(button) {
        }
References m_Button.
Referenced by Vesper::MouseButtonPressedEvent::MouseButtonPressedEvent(), and Vesper::MouseButtonReleasedEvent::MouseButtonReleasedEvent().
Member Function Documentation
GetMouseButton()
int Vesper::MouseButtonEvent::GetMouseButton () const [inline]
Get the mouse button associated with the event.
{ return m_Button; }
References m_Button.
Referenced by Vesper::MouseButtonPressedEvent::ToString(), and Vesper::MouseButtonReleasedEvent::ToString().
Member Data Documentation
m_Button
int Vesper::MouseButtonEvent::m_Button [protected]
Referenced by GetMouseButton(), and MouseButtonEvent().
The documentation for this class was generated from the following file:
Vesper/src/Vesper/Events/MouseEvent.h