Vesper::Input Class Reference
Base input class for querying input states.
#include <Input.h>
Public Member Functions
Input (const Input &)=delete
Input & operator= (const Input &)=delete
Static Public Member Functions
static bool IsKeyPressed (int keycode)
Checks if the specified key is currently pressed.
static bool IsMouseButtonPressed (int button)
Checks if the specified mouse button is currently pressed.
static float GetMouseX ()
Gets the current X position of the mouse cursor.
static float GetMouseY ()
Gets the current Y position of the mouse cursor.
static glm::vec2 GetMousePosition ()
Gets the current position of the mouse cursor as a 2D vector.
Protected Member Functions
Input ()=default
Detailed Description
Base input class for querying input states.
Constructor & Destructor Documentation
Input() [1/2]
Vesper::Input::Input () [protected], [default]
Input() [2/2]
Vesper::Input::Input (const Input &) [delete]
Member Function Documentation
GetMousePosition()
glm::vec2 Vesper::Input::GetMousePosition () [static]
Gets the current position of the mouse cursor as a 2D vector.
    {
        auto window = static_cast<GLFWwindow*>(Application::Get().GetWindow().GetNativeWindow());
        double xPos, yPos;
        glfwGetCursorPos(window, &xPos, &yPos);
        return { (float)xPos, (float)yPos };
    }
References Vesper::Application::Get(), Vesper::Window::GetNativeWindow(), and Vesper::Application::GetWindow().
GetMouseX()
float Vesper::Input::GetMouseX () [static]
Gets the current X position of the mouse cursor.
    {
        return GetMousePosition().x;
    }
GetMouseY()
float Vesper::Input::GetMouseY () [static]
Gets the current Y position of the mouse cursor.
    {
        return GetMousePosition().y;
    }
IsKeyPressed()
bool Vesper::Input::IsKeyPressed (int keycode) [static]
Checks if the specified key is currently pressed.
Parameters
keycode The keycode of the key to check.
Returns
True if the key is pressed, false otherwise.
    {
        auto window = static_cast<GLFWwindow*>(Application::Get().GetWindow().GetNativeWindow());
        auto state = glfwGetKey(window, keycode);
        return state == GLFW_PRESS || state == GLFW_REPEAT;
    }
References Vesper::Application::Get(), Vesper::Window::GetNativeWindow(), and Vesper::Application::GetWindow().
Referenced by Vesper::EditorLayer::OnImGuiRender(), Vesper::EditorLayer::OnKeyPressed(), Vesper::EditorCamera::OnUpdate(), and Vesper::OrthographicCameraController::OnUpdate().
IsMouseButtonPressed()
bool Vesper::Input::IsMouseButtonPressed (int button) [static]
Checks if the specified mouse button is currently pressed.
Parameters
button The mouse button to check.
Returns
True if the mouse button is pressed, false otherwise.
    {
        auto window = static_cast<GLFWwindow*>(Application::Get().GetWindow().GetNativeWindow());
        auto state = glfwGetMouseButton(window, button);
        return state == GLFW_PRESS;
    }
References Vesper::Application::Get(), Vesper::Window::GetNativeWindow(), and Vesper::Application::GetWindow().
Referenced by Vesper::EditorCamera::OnUpdate(), and Vesper::EditorLayer::OnUpdate().
operator=()
Input & Vesper::Input::operator= (const Input &) [delete]
The documentation for this class was generated from the following files:
Vesper/src/Vesper/Input/Input.h
Vesper/src/Platform/Windows/WindowsInput.cpp