Vesper::FileSystem Class Reference
#include <PlatformUtils.h>
Static Public Member Functions
static void Initialize ()
static std::string GetCurrentWorkingDirectory ()
static std::string GetAbsolutePath (const std::string &relativePath)
static std::string GetTravelingUpPath (const std::string &path)
static bool IsInitialized ()
Static Public Attributes
static bool m_Initialized = false
static std::string m_RootEngineDirectory = ""
static std::string m_RootEditorDirectory = ""
static std::string m_ResourcesDirectory = ""
static std::string m_AssetsDirectory = ""
static std::string m_ProjectsDirectory = ""
static std::string m_CurrentProjectDirectory = ""
Member Function Documentation
GetAbsolutePath()
std::string Vesper::FileSystem::GetAbsolutePath (const std::string & relativePath) [static]
                                                                       {
        char fullPath[MAX_PATH];
        if (_fullpath(fullPath, relativePath.c_str(), MAX_PATH) != nullptr) {
            return std::string(fullPath);
        }
        return std::string();
    }
Referenced by Initialize().
GetCurrentWorkingDirectory()
std::string Vesper::FileSystem::GetCurrentWorkingDirectory () [static]
                                                     {
        CHAR currentDir[256] = { 0 };
        if (GetCurrentDirectoryA(256, currentDir))
            return std::string(currentDir);
        return std::string();
    }
GetTravelingUpPath()
std::string Vesper::FileSystem::GetTravelingUpPath (const std::string & path) [static]
                                                                  {
        size_t pos = path.find_last_of("/\\");
        if (pos != std::string::npos) {
            return path.substr(0, pos);
        }
        return std::string();
    }
Referenced by Initialize().
Initialize()
void Vesper::FileSystem::Initialize () [static]
                                {
        if (m_Initialized)
            return;
        m_Initialized = true;
        // Set Root Engine Directory
        m_RootEngineDirectory = GetTravelingUpPath(GetTravelingUpPath(GetTravelingUpPath(GetAbsolutePath("."))));
        // Set Root Editor Directory
        m_RootEditorDirectory = GetAbsolutePath("../../Vesper-Editor/");
        // Set Resources Directory
        m_ResourcesDirectory = GetAbsolutePath(m_RootEngineDirectory + "/Resources/");
        // Set Assets Directory
        m_AssetsDirectory = GetAbsolutePath(m_RootEditorDirectory + "/assets");
        // Set Projects Directory
        m_ProjectsDirectory = GetAbsolutePath(m_RootEngineDirectory + "/Projects");
        // Set Current Project Directory
        m_CurrentProjectDirectory = GetAbsolutePath(m_ProjectsDirectory + "/DefaultProject");
        // Log Directories for Debugging
        VZ_CORE_TRACE("FileSystem initialized");
        VZ_CORE_TRACE("FileSystem Directories:");
        VZ_CORE_TRACE("Root Engine Directory : " + m_RootEngineDirectory);
        VZ_CORE_TRACE("Root Editor Directory : " + m_RootEditorDirectory);
        VZ_CORE_TRACE("Resources Directory : " + m_ResourcesDirectory);
        VZ_CORE_TRACE("Assets Directory : " + m_AssetsDirectory);
        VZ_CORE_TRACE("Projects Directory : " + m_ProjectsDirectory);
        VZ_CORE_TRACE("Current Project Directory : " + m_CurrentProjectDirectory);
    }
References GetAbsolutePath(), GetTravelingUpPath(), and m_Initialized.
Referenced by Vesper::EditorLayer::OnAttach().
IsInitialized()
bool Vesper::FileSystem::IsInitialized () [inline], [static]
{ return m_Initialized; }
References m_Initialized.
Member Data Documentation
m_AssetsDirectory
std::string Vesper::FileSystem::m_AssetsDirectory = "" [static]
m_CurrentProjectDirectory
std::string Vesper::FileSystem::m_CurrentProjectDirectory = "" [static]
m_Initialized
bool Vesper::FileSystem::m_Initialized = false [static]
Referenced by Initialize(), and IsInitialized().
m_ProjectsDirectory
std::string Vesper::FileSystem::m_ProjectsDirectory = "" [static]
m_ResourcesDirectory
std::string Vesper::FileSystem::m_ResourcesDirectory = "" [static]
m_RootEditorDirectory
std::string Vesper::FileSystem::m_RootEditorDirectory = "" [static]
m_RootEngineDirectory
std::string Vesper::FileSystem::m_RootEngineDirectory = "" [static]
The documentation for this class was generated from the following files:
Vesper/src/Vesper/Utils/PlatformUtils.h
Vesper/src/Platform/Windows/WindowsPlatformUtils.cpp