Vesper::ImGuiLayer Class Reference
#include <ImGuiLayer.h>
Public Member Functions
ImGuiLayer ()
~ImGuiLayer ()
virtual void OnAttach () override
Called when the layer is attached to the application.
virtual void OnDetach () override
Called when the layer is detached from the application.
virtual void OnImGuiRender () override
Called when the layer should render its ImGui components.
virtual void OnEvent (Event &e) override
Called when an event is dispatched to the layer.
virtual void Begin ()
virtual void End ()
virtual void SetBlockEvents (bool block)
virtual void SetDarkThemeColors ()
Public Member Functions inherited from Vesper::Layer
Layer (const std::string &name="Layer")
Constructs a Layer with an optional name for debugging purposes.
virtual ~Layer ()
virtual void OnUpdate (Timestep ts)
Called every frame to update the layer with the given timestep.
virtual void OnRender ()
Called when the layer should render its contents.
const std::string & GetName () const
Retrieves the name of the layer for debugging purposes.
Protected Attributes
bool m_BlockEvents = true
float m_Time = 0.0f
Protected Attributes inherited from Vesper::Layer
std::string m_DebugName
The name of the layer assigned at creation, used for debugging.
Constructor & Destructor Documentation
ImGuiLayer()
Vesper::ImGuiLayer::ImGuiLayer ()
                           : Layer("ImGuiLayer")
    {
    }
Referenced by Vesper::Application::Application(), and Vesper::OpenGLImGuiLayer::OpenGLImGuiLayer().
~ImGuiLayer()
Vesper::ImGuiLayer::~ImGuiLayer ()
    {
    }
Member Function Documentation
Begin()
void Vesper::ImGuiLayer::Begin () [virtual]
Reimplemented in Vesper::OpenGLImGuiLayer.
    {
        VZ_PROFILE_FUNCTION();
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();
        ImGuizmo::BeginFrame();
    }
Referenced by Vesper::OpenGLImGuiLayer::Begin(), and Vesper::Application::Run().
End()
void Vesper::ImGuiLayer::End () [virtual]
Reimplemented in Vesper::OpenGLImGuiLayer.
    {
        VZ_PROFILE_FUNCTION();
        ImGuiIO& io = ImGui::GetIO();
        Application& app = Application::Get();
        io.DisplaySize = ImVec2((float)app.GetWindow().GetWidth(), (float)app.GetWindow().GetHeight());
        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
        if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
        {
            GLFWwindow* backup_current_context = glfwGetCurrentContext();
            ImGui::UpdatePlatformWindows();
            ImGui::RenderPlatformWindowsDefault();
            glfwMakeContextCurrent(backup_current_context);
        }
    }
References Vesper::Application::Get(), Vesper::Window::GetHeight(), Vesper::Window::GetWidth(), and Vesper::Application::GetWindow().
Referenced by Vesper::OpenGLImGuiLayer::End(), and Vesper::Application::Run().
OnAttach()
void Vesper::ImGuiLayer::OnAttach () [override], [virtual]
Called when the layer is attached to the application.
TODO: Remove to openGL specific
Reimplemented from Vesper::Layer.
Reimplemented in Vesper::OpenGLImGuiLayer.
    {
        VZ_PROFILE_FUNCTION();
        IMGUI_CHECKVERSION();
        ImGui::CreateContext();
        ImGuiIO& io = ImGui::GetIO(); (void)io;
        //io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard; // Enable Keyboard Controls
        //io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad; // Enable Gamepad Controls
        io.ConfigFlags |= ImGuiConfigFlags_DockingEnable; // Enable Docking
        io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable; // Enable Multi-Viewport / Platform Windows
        //io.ConfigFlags |= ImGuiConfigFlags_ViewportsNoTaskBarIcons; // Disable Platform Windows task bar icons
        //io.ConfigFlags |= ImGuiConfigFlags_ViewportsNoMerge; // Disable Platform Windows merging into host window
        io.Fonts->AddFontFromFileTTF("../../Vesper-Editor/assets/fonts/RedHatMono/static/RedHatMono-Bold.ttf", 18.0f);
        io.FontDefault = io.Fonts->AddFontFromFileTTF("../../Vesper-Editor/assets/fonts/RedHatMono/static/RedHatMono-Light.ttf", 18.0f);
        ImGui::StyleColorsDark();
        // When viewports are enabled we tweak WindowRounding/WindowBg so platform windows can look identical to regular ones.
        ImGuiStyle& style = ImGui::GetStyle();
        if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
        {
            style.WindowRounding = 0.0f;
            style.Colors[ImGuiCol_WindowBg].w = 1.0f;
        }
        SetDarkThemeColors();
        {
            Application& app = Application::Get();
            GLFWwindow* window = static_cast<GLFWwindow*>(app.GetWindow().GetNativeWindow());
            ImGui_ImplGlfw_InitForOpenGL(window, true);
            ImGui_ImplOpenGL3_Init("#version 410");
        }
    }
References Vesper::Application::Get(), and SetDarkThemeColors().
Referenced by Vesper::OpenGLImGuiLayer::OnAttach().
OnDetach()
void Vesper::ImGuiLayer::OnDetach () [override], [virtual]
Called when the layer is detached from the application.
TODO: Remove to openGL specific
Reimplemented from Vesper::Layer.
Reimplemented in Vesper::OpenGLImGuiLayer.
    {
        VZ_PROFILE_FUNCTION();
        {
            ImGui_ImplOpenGL3_Shutdown();
            ImGui_ImplGlfw_Shutdown();
            ImGui::DestroyContext();
        }
    }
Referenced by Vesper::OpenGLImGuiLayer::OnDetach().
OnEvent()
void Vesper::ImGuiLayer::OnEvent (Event & event) [override], [virtual]
Called when an event is dispatched to the layer.
Parameters
event The event being dispatched.
Reimplemented from Vesper::Layer.
Reimplemented in Vesper::OpenGLImGuiLayer.
    {
        if (m_BlockEvents) {
            ImGuiIO& io = ImGui::GetIO();
            e.Handled |= e.IsInCategory(EventCategoryMouse) & io.WantCaptureMouse;
            e.Handled |= e.IsInCategory(EventCategoryKeyboard) & io.WantCaptureKeyboard;
        }
    }
References Vesper::EventCategoryKeyboard, Vesper::EventCategoryMouse, Vesper::Event::Handled, Vesper::Event::IsInCategory(), and m_BlockEvents.
Referenced by Vesper::OpenGLImGuiLayer::OnEvent().
OnImGuiRender()
void Vesper::ImGuiLayer::OnImGuiRender () [override], [virtual]
Called when the layer should render its ImGui components.
Reimplemented from Vesper::Layer.
Reimplemented in Vesper::OpenGLImGuiLayer.
    {
    }
Referenced by Vesper::OpenGLImGuiLayer::OnImGuiRender().
SetBlockEvents()
virtual void Vesper::ImGuiLayer::SetBlockEvents (bool block) [inline], [virtual]
Reimplemented in Vesper::OpenGLImGuiLayer.
{ m_BlockEvents = block; }
References m_BlockEvents.
Referenced by Vesper::EditorLayer::OnImGuiRender().
SetDarkThemeColors()
void Vesper::ImGuiLayer::SetDarkThemeColors () [virtual]
Reimplemented in Vesper::OpenGLImGuiLayer.
    {
        auto& colors = ImGui::GetStyle().Colors;
        colors[ImGuiCol_WindowBg] = ImVec4{ 0.1f, 0.105f, 0.11f, 1.0f };
        // Header
        colors[ImGuiCol_Header] = ImVec4{ 0.2f, 0.205f, 0.21f, 1.0f };
        colors[ImGuiCol_HeaderHovered] = ImVec4{ 0.3f, 0.305f, 0.31f, 1.0f };
        colors[ImGuiCol_HeaderActive] = ImVec4{ 0.15f, 0.1505f, 0.151f, 1.0f };
        // Buttons
        colors[ImGuiCol_Button] = ImVec4{ 0.2f, 0.205f, 0.21f, 1.0f };
        colors[ImGuiCol_ButtonHovered] = ImVec4{ 0.3f, 0.305f, 0.31f, 1.0f };
        colors[ImGuiCol_ButtonActive] = ImVec4{ 0.15f, 0.1505f, 0.151f, 1.0f };
        // Frame BG
        colors[ImGuiCol_FrameBg] = ImVec4{ 0.2f, 0.205f, 0.21f, 1.0f };
        colors[ImGuiCol_FrameBgHovered] = ImVec4{ 0.3f, 0.305f, 0.31f, 1.0f };
        colors[ImGuiCol_FrameBgActive] = ImVec4{ 0.15f, 0.1505f, 0.151f, 1.0f };
        // Tabs
        colors[ImGuiCol_Tab] = ImVec4{ 0.15f, 0.1505f, 0.151f, 1.0f };
        colors[ImGuiCol_TabHovered] = ImVec4{ 0.38f, 0.3805f, 0.381f, 1.0f };
        colors[ImGuiCol_TabActive] = ImVec4{ 0.28f, 0.2805f, 0.281f, 1.0f };
        colors[ImGuiCol_TabUnfocused] = ImVec4{ 0.15f, 0.1505f, 0.151f, 1.0f };
        colors[ImGuiCol_TabUnfocusedActive] = ImVec4{ 0.2f, 0.205f, 0.21f, 1.0f };
        // Title
        colors[ImGuiCol_TitleBg] = ImVec4{ 0.1f, 0.105f, 0.11f, 1.0f };
        colors[ImGuiCol_TitleBgActive] = ImVec4{ 0.1f, 0.105f, 0.11f, 1.0f };
        colors[ImGuiCol_TitleBgCollapsed] = ImVec4{ 0.1f, 0.105f, 0.11f, 1.0f };
    }
Referenced by OnAttach(), and Vesper::OpenGLImGuiLayer::SetDarkThemeColors().
Member Data Documentation
m_BlockEvents
bool Vesper::ImGuiLayer::m_BlockEvents = true [protected]
Referenced by OnEvent(), SetBlockEvents(), and Vesper::OpenGLImGuiLayer::SetBlockEvents().
m_Time
float Vesper::ImGuiLayer::m_Time = 0.0f [protected]
The documentation for this class was generated from the following files:
Vesper/src/Vesper/ImGui/ImGuiLayer.h
Vesper/src/Vesper/ImGui/ImGuiLayer.cpp