Vesper::Application Class Reference
#include <Application.h>
Public Member Functions
Application (const std::string &name="")
virtual ~Application ()
void Run ()
void OnEvent (Event &e)
void PushLayer (Layer *layer)
void PushOverlay (Layer *overlay)
void Close ()
ImGuiLayer * GetImGuiLayer ()
Window & GetWindow ()
Static Public Member Functions
static Application & Get ()
Private Member Functions
bool OnWindowClose (WindowCloseEvent &e)
bool OnWindowResize (WindowResizeEvent &e)
Private Attributes
Scope< Window > m_Window
ImGuiLayer * m_ImGuiLayer
bool m_Running = true
bool m_Minimized = false
LayerStack m_LayerStack
float m_LastFrameTime = 0.0f
Static Private Attributes
static Application * s_Instance = nullptr
Constructor & Destructor Documentation
Application()
Vesper::Application::Application (const std::string & name = "")
    {
        VZ_PROFILE_FUNCTION();
        VZ_CORE_ASSERT(!s_Instance, "Application already exists!");
        s_Instance = this;
        m_Window = Window::Create(WindowProps(name));
        m_Window->SetEventCallback(BIND_EVENT_FN(OnEvent));
        m_Window->SetVSync(false);
        Renderer::Init();
        m_ImGuiLayer = new ImGuiLayer();
        PushOverlay(m_ImGuiLayer);
    }
References Vesper::ImGuiLayer::ImGuiLayer(), Vesper::Renderer::Init(), m_ImGuiLayer, PushOverlay(), and s_Instance.
~Application()
Vesper::Application::~Application () [virtual]
    {
    }
Member Function Documentation
Close()
void Vesper::Application::Close ()
    {
        m_Running = false;
    }
References m_Running.
Referenced by Vesper::EditorLayer::OnImGuiRender().
Get()
Application & Vesper::Application::Get () [inline], [static]
{ return *s_Instance; }
References s_Instance.
Referenced by Vesper::ImGuiLayer::End(), Vesper::Input::GetMousePosition(), Vesper::Input::IsKeyPressed(), Vesper::Input::IsMouseButtonPressed(), Vesper::ImGuiLayer::OnAttach(), and Vesper::EditorLayer::OnImGuiRender().
GetImGuiLayer()
ImGuiLayer * Vesper::Application::GetImGuiLayer () [inline]
{ return m_ImGuiLayer; }
References m_ImGuiLayer.
Referenced by Vesper::EditorLayer::OnImGuiRender().
GetWindow()
Window & Vesper::Application::GetWindow () [inline]
{ return *m_Window; }
Referenced by Vesper::ImGuiLayer::End(), Vesper::Input::GetMousePosition(), Vesper::Input::IsKeyPressed(), and Vesper::Input::IsMouseButtonPressed().
OnEvent()
void Vesper::Application::OnEvent (Event & e)
    {
        VZ_PROFILE_FUNCTION();
        EventDispatcher dispatcher(e);
        dispatcher.Dispatch<WindowCloseEvent>(BIND_EVENT_FN(OnWindowClose));
        dispatcher.Dispatch<WindowResizeEvent>(BIND_EVENT_FN(OnWindowResize));
        for (auto it = m_LayerStack.rbegin(); it != m_LayerStack.rend(); ++it)
        {
            if (e.Handled)
                break;
            (*it)->OnEvent(e);
        }
    }
References Vesper::EventDispatcher::EventDispatcher(), OnWindowClose(), and OnWindowResize().
OnWindowClose()
bool Vesper::Application::OnWindowClose (WindowCloseEvent & e) [private]
    {
        VZ_PROFILE_FUNCTION();
        m_Running = false;
        return true;
    }
References m_Running.
Referenced by OnEvent().
OnWindowResize()
bool Vesper::Application::OnWindowResize (WindowResizeEvent & e) [private]
    {
        VZ_PROFILE_FUNCTION();
        if (e.GetWidth() == 0 || e.GetHeight() == 0)
        {
            m_Minimized = true;
            return false;
        }
        m_Minimized = false;
        Renderer::OnWindowResize(e.GetWidth(), e.GetHeight());
        return false;
    }
References Vesper::WindowResizeEvent::GetHeight(), Vesper::WindowResizeEvent::GetWidth(), m_Minimized, and Vesper::Renderer::OnWindowResize().
Referenced by OnEvent().
PushLayer()
void Vesper::Application::PushLayer (Layer * layer)
    {
        VZ_PROFILE_FUNCTION();
        m_LayerStack.PushLayer(layer);
        layer->OnAttach();
    }
References Vesper::Layer::OnAttach().
Referenced by Vesper::VesperEditor::VesperEditor().
PushOverlay()
void Vesper::Application::PushOverlay (Layer * overlay)
    {
        VZ_PROFILE_FUNCTION();
        m_LayerStack.PushOverlay(overlay);
        overlay->OnAttach();
    }
References Vesper::Layer::OnAttach().
Referenced by Application().
Run()
void Vesper::Application::Run ()
    {
        VZ_PROFILE_FUNCTION();
        while (m_Running)
        {
            VZ_PROFILE_SCOPE("RunLoop");
            float time = (float)glfwGetTime(); // TODO: Platform::GetTime()
            Timestep timestep = time - m_LastFrameTime;
            m_LastFrameTime = time;
            if (!m_Minimized)
            {
                VZ_PROFILE_SCOPE("LayerStack OnUpdate");
                // Update layers
                for (auto layer : m_LayerStack)
                    layer->OnUpdate(timestep);
            }
            {
                VZ_PROFILE_SCOPE("ImGuiLayer OnImGuiRender");
                m_ImGuiLayer->Begin();
                for (auto layer : m_LayerStack)
                    layer->OnImGuiRender();
                m_ImGuiLayer->End();
            }
            {
                VZ_PROFILE_SCOPE("Window OnUpdate");
                // Update window second
                m_Window->OnUpdate();
            }
        };
    }
References Vesper::ImGuiLayer::Begin(), Vesper::ImGuiLayer::End(), m_ImGuiLayer, m_LastFrameTime, m_Minimized, and m_Running.
Member Data Documentation
m_ImGuiLayer
ImGuiLayer* Vesper::Application::m_ImGuiLayer [private]
Referenced by Application(), GetImGuiLayer(), and Run().
m_LastFrameTime
float Vesper::Application::m_LastFrameTime = 0.0f [private]
Referenced by Run().
m_LayerStack
LayerStack Vesper::Application::m_LayerStack [private]
m_Minimized
bool Vesper::Application::m_Minimized = false [private]
Referenced by OnWindowResize(), and Run().
m_Running
bool Vesper::Application::m_Running = true [private]
Referenced by Close(), OnWindowClose(), and Run().
m_Window
Scope<Window> Vesper::Application::m_Window [private]
s_Instance
Application * Vesper::Application::s_Instance = nullptr [static], [private]
Referenced by Application(), and Get().
The documentation for this class was generated from the following files:
Vesper/src/Vesper/App/Application.h
Vesper/src/Vesper/App/Application.cpp