Vesper::OpenGLImGuiLayer Class Reference
#include <OpenGLImGuiLayer.h>
Public Member Functions
OpenGLImGuiLayer ()
~OpenGLImGuiLayer ()
virtual void OnAttach () override
Called when the layer is attached to the application.
virtual void OnDetach () override
Called when the layer is detached from the application.
virtual void OnImGuiRender () override
Called when the layer should render its ImGui components.
virtual void OnEvent (Event &e) override
Called when an event is dispatched to the layer.
virtual void Begin () override
virtual void End () override
virtual void SetBlockEvents (bool block)
virtual void SetDarkThemeColors () override
Public Member Functions inherited from Vesper::ImGuiLayer
ImGuiLayer ()
~ImGuiLayer ()
Public Member Functions inherited from Vesper::Layer
Layer (const std::string &name="Layer")
Constructs a Layer with an optional name for debugging purposes.
virtual ~Layer ()
virtual void OnUpdate (Timestep ts)
Called every frame to update the layer with the given timestep.
virtual void OnRender ()
Called when the layer should render its contents.
const std::string & GetName () const
Retrieves the name of the layer for debugging purposes.
Additional Inherited Members
Protected Attributes inherited from Vesper::ImGuiLayer
bool m_BlockEvents = true
float m_Time = 0.0f
Protected Attributes inherited from Vesper::Layer
std::string m_DebugName
The name of the layer assigned at creation, used for debugging.
Constructor & Destructor Documentation
OpenGLImGuiLayer()
Vesper::OpenGLImGuiLayer::OpenGLImGuiLayer ()
                                       : ImGuiLayer()
    {
    }
References Vesper::ImGuiLayer::ImGuiLayer().
~OpenGLImGuiLayer()
Vesper::OpenGLImGuiLayer::~OpenGLImGuiLayer ()
    {
    }
Member Function Documentation
Begin()
void Vesper::OpenGLImGuiLayer::Begin () [override], [virtual]
Reimplemented from Vesper::ImGuiLayer.
    {
        ImGuiLayer::Begin();
    }
References Vesper::ImGuiLayer::Begin().
End()
void Vesper::OpenGLImGuiLayer::End () [override], [virtual]
Reimplemented from Vesper::ImGuiLayer.
    {
        ImGuiLayer::End();
    }
References Vesper::ImGuiLayer::End().
OnAttach()
void Vesper::OpenGLImGuiLayer::OnAttach () [override], [virtual]
Called when the layer is attached to the application.
Reimplemented from Vesper::ImGuiLayer.
    {
        ImGuiLayer::OnAttach();
    }
References Vesper::ImGuiLayer::OnAttach().
OnDetach()
void Vesper::OpenGLImGuiLayer::OnDetach () [override], [virtual]
Called when the layer is detached from the application.
Reimplemented from Vesper::ImGuiLayer.
    {
        ImGuiLayer::OnDetach();
    }
References Vesper::ImGuiLayer::OnDetach().
OnEvent()
void Vesper::OpenGLImGuiLayer::OnEvent (Event & event) [override], [virtual]
Called when an event is dispatched to the layer.
Parameters
event The event being dispatched.
Reimplemented from Vesper::ImGuiLayer.
    {
        ImGuiLayer::OnEvent(e);
    }
References Vesper::ImGuiLayer::OnEvent().
OnImGuiRender()
void Vesper::OpenGLImGuiLayer::OnImGuiRender () [override], [virtual]
Called when the layer should render its ImGui components.
Reimplemented from Vesper::ImGuiLayer.
    {
        ImGuiLayer::OnImGuiRender();
    }
References Vesper::ImGuiLayer::OnImGuiRender().
SetBlockEvents()
virtual void Vesper::OpenGLImGuiLayer::SetBlockEvents (bool block) [inline], [virtual]
Reimplemented from Vesper::ImGuiLayer.
{ m_BlockEvents = block; }
References Vesper::ImGuiLayer::m_BlockEvents.
SetDarkThemeColors()
void Vesper::OpenGLImGuiLayer::SetDarkThemeColors () [override], [virtual]
Reimplemented from Vesper::ImGuiLayer.
    {
        ImGuiLayer::SetDarkThemeColors();
    }
References Vesper::ImGuiLayer::SetDarkThemeColors().
The documentation for this class was generated from the following files:
Vesper/src/RenderAPI/OpenGL/OpenGLImGuiLayer.h
Vesper/src/RenderAPI/OpenGL/OpenGLImGuiLayer.cpp