Vesper::BufferElement Struct Reference
#include <Buffer.h>
Public Member Functions
BufferElement ()
BufferElement (ShaderDataType type, const std::string &name, bool normalized=false)
uint32_t GetComponentCount () const
Public Attributes
std::string Name
ShaderDataType Type
uint32_t Size
uint32_t Offset
bool Normalized
Constructor & Destructor Documentation
BufferElement() [1/2]
Vesper::BufferElement::BufferElement () [inline]
{}
BufferElement() [2/2]
Vesper::BufferElement::BufferElement (ShaderDataType type, const std::string & name, bool normalized = false) [inline]
            : Name(name), Type(type), Size(ShaderDataTypeSize(type)), Offset(0), Normalized(normalized)
        {
        }
References BufferElement(), Normalized, Offset, Vesper::ShaderDataTypeSize(), Size, and Type.
Referenced by BufferElement().
Member Function Documentation
GetComponentCount()
uint32_t Vesper::BufferElement::GetComponentCount () const [inline]
                                           {
            switch (Type) {
            case ShaderDataType::Float: return 1;
            case ShaderDataType::Float2: return 2;
            case ShaderDataType::Float3: return 3;
            case ShaderDataType::Float4: return 4;
            case ShaderDataType::Mat3: return 3 * 3;
            case ShaderDataType::Mat4: return 4 * 4;
            case ShaderDataType::Int: return 1;
            case ShaderDataType::Int2: return 2;
            case ShaderDataType::Int3: return 3;
            case ShaderDataType::Int4: return 4;
            case ShaderDataType::Bool: return 1;
            }
            VZ_CORE_ASSERT(false, "Unknown ShaderDataType!");
            return 0;
        }
References Vesper::Bool, Vesper::Float, Vesper::Float2, Vesper::Float3, Vesper::Float4, Vesper::Int, Vesper::Int2, Vesper::Int3, Vesper::Int4, Vesper::Mat3, Vesper::Mat4, and Type.
Member Data Documentation
Name
std::string Vesper::BufferElement::Name
Normalized
bool Vesper::BufferElement::Normalized
Referenced by BufferElement().
Offset
uint32_t Vesper::BufferElement::Offset
Referenced by BufferElement().
Size
uint32_t Vesper::BufferElement::Size
Referenced by BufferElement().
Type
ShaderDataType Vesper::BufferElement::Type
Referenced by BufferElement(), and GetComponentCount().
The documentation for this struct was generated from the following file:
Vesper/src/Vesper/Renderer/Buffer.h